### ISSUE TITLE
First search on Windows leads to a lock-up of a few seconds

### ISSUE THREAD

**Issue by erik-brangs** [tomboy-notes/tomboy-ng#179] opened 2020-05-02 07:24 UTC
The first search on tomboy-ng on Windows (currently using 0.28b) on my machine leads to tomboy-ng not reacting for a few seconds (roughly 1-2 seconds). Subsequent searches are fast. 

This problem does not occur on Linux.

I've had this problem for a while. I mentioned it in #29 when I was using my old computer. Now I'm using a much newer computer with fast SSDs and I'm still having the same problem.

**Comment by davidbannon** [comment] 2020-05-02 08:37
Erik, is that a search within a note or from the Search window across all notes ?

When you say "Subsequent searches are fast.", what has to happen to go back to the delay ?  A period of time without any searches, restart of tomboy-ng or a restart of windows ?

From memory, you have quite a lot of notes ?

My first attempt to replicate across notes on windows was unsuccessful, but I have only three hundred or so notes ....

Davo

**Comment by erik-brangs** [comment] 2020-05-02 09:15
The search is from the Search windows across all notes. The delay comes back after a period of time without any searches. A restart of tomboy-ng doesn't trigger it, but a restart of windows does.

I've got ~ 2000 notes right now.

**Comment by davidbannon** [comment] 2020-05-02 10:01
Hmm, I was sure I had a tool to make lots of new notes, cannot find it.  Will have to make another one .....
Will get back to you.
Davo

**Comment by davidbannon** [comment] 2020-05-02 13:24
OK, I generated 5000 notes based on a small number of existing ones and put those in place of my notes on my Windows  box. But I cannot replicate your problem. In fact, I am astounded how fast it seems, Windows seems to be able to handle large numbers of files in one dir a lot better than it used to.

Now, a couple of things, firstly, the delay you see, that happens when you press enter after entering your search term, right ?   Its not a delay while we fill in string grid with all the note names in it, that is while the search form itself opens up ?

Secondly, do you have auto sync turned on ?  It starts up 15 seconds after you startup tomboy-ng. I did a very, very stupid thing, I had auto sync on when I fired up with those 5000 notes !  So, after the 15 second delay, it started streaming all those dummy notes to the sync repo .....
That sure locked things up, I can tell you !

I am using a laptop but with an SSD and 16G ram, I might try repeating my experiments on a more modest Windows box tomorrow.  Maybe with bigger files ....

But I am wondering if its just Windows caching there, it initially reads from the disk, then subsquent searches come from cache, then, after awhile, the cache data gets replaced with whatever else you are doing, so, when you come back to tomboy-ng, initially its slow again.

Davo

**Comment by erik-brangs** [comment] 2020-05-02 14:10
The delay is after entering the search term.

Auto-Sync is turned off.

**Comment by davidbannon** [comment] 2020-05-03 11:10
OK Erik, I cannot see this problem I am afraid.
Attached is a zip file with a new (64bit) windows binary.  It has some timing measurements
[tb-v28c.zip](https://github.com/tomboy-notes/tomboy-ng/files/4570141/tb-v28c.zip)
 that it can be tricked into writing to a log file.  It does not need to be installed. Here is what I did -
Important - stop an existing instance of tomboy-ng.
Unzipped and drag the binary onto the desktop.
rightclick start button and select 'run', into that field type this (inc double inverted commas) -
"%userprofile%\tomboy-ng.exe" --debug-index --debug-log=%userprofile%\Desktop\tomboy-log.txt

The logfile is only a couple of lines long, please post !

[tb-v28c.zip](https://github.com/tomboy-notes/tomboy-ng/files/4570141/tb-v28c.zip)

In my case, the first search took about 50% longer that subsequent ones. Less than a second.

Davo

**Comment by erik-brangs** [comment] 2020-05-03 13:06
It seems I can't reproduce it as reliable as I thought. However, the problem did occur. Here's a longer logfile (problematic search is roughly in the middle):

Empty Note and Book Lists created
Looking for notes in [C:\Users\Erik Brangs\Desktop\]
Finished indexing notes
Empty Note and Book Lists created
Looking for notes in [C:\Users\Erik Brangs\AppData\Roaming\tomboy-ng\notes\]
Finished indexing notes
NoteLister : BuildSearchList 0mS
Empty Search Lists created
Looking for notes in [C:\Users\Erik Brangs\AppData\Roaming\tomboy-ng\notes\]
Finished indexing notes
Search Speed from SearchUnit 250mS 453mS
NoteLister : BuildSearchList 0mS
Empty Search Lists created
Looking for notes in [C:\Users\Erik Brangs\AppData\Roaming\tomboy-ng\notes\]
Finished indexing notes
Search Speed from SearchUnit 235mS 93mS
Empty Note and Book Lists created
Looking for notes in [C:\Users\Erik Brangs\Desktop\]
Finished indexing notes
Empty Note and Book Lists created
Looking for notes in [C:\Users\Erik Brangs\AppData\Roaming\tomboy-ng\notes\]
Finished indexing notes
NoteLister : BuildSearchList 0mS
Empty Search Lists created
Looking for notes in [C:\Users\Erik Brangs\AppData\Roaming\tomboy-ng\notes\]
Finished indexing notes
Search Speed from SearchUnit 7594mS 437mS
NoteLister : BuildSearchList 0mS
Empty Search Lists created
Looking for notes in [C:\Users\Erik Brangs\AppData\Roaming\tomboy-ng\notes\]
Finished indexing notes
Search Speed from SearchUnit 219mS 62mS
NoteLister : BuildSearchList 0mS
Empty Search Lists created
Looking for notes in [C:\Users\Erik Brangs\AppData\Roaming\tomboy-ng\notes\]
Finished indexing notes
Search Speed from SearchUnit 203mS 62mS
Empty Note and Book Lists created
Looking for notes in [C:\Users\Erik Brangs\Desktop\]
Finished indexing notes
Empty Note and Book Lists created
Looking for notes in [C:\Users\Erik Brangs\AppData\Roaming\tomboy-ng\notes\]
Finished indexing notes
NoteLister : BuildSearchList 0mS
Empty Search Lists created
Looking for notes in [C:\Users\Erik Brangs\AppData\Roaming\tomboy-ng\notes\]
Finished indexing notes
Search Speed from SearchUnit 219mS 375mS

**Comment by davidbannon** [comment] 2020-05-04 00:20
Ah, sorry Erik, I mistakenly left  --debug-index  in those instructions, unnecessary waffle in the log but does no harm.

It looks to me as if you did two searches that were quite fast, then one that bogged right down.  That says its not a caching thing.  And jumping from 0.2 seconds to 7.5 needs to be explained.

If you don't mind, I will try to zoom in a bit closer to isolate the area thats using the time. I will send you another test app.  

Idle speculation, have you looked at your system monitor to see if there are spikes of cpu usage from time to time ?  Maybe a virus scanner, update manager of something like that ?   I am assuming your new system has multiple cores and should be relatively resistant to such problems but I am guessing .....

Davo

**Comment by davidbannon** [comment] 2020-05-04 03:20
[tb-v28d.zip](https://github.com/tomboy-notes/tomboy-ng/files/4572635/tb-v28d.zip)

OK Erik, same model, you can leave out the "--debug-index" bit but it does not matter.  Note this new binary has same name as the one I sent you yesterday, make sure it overwrites it.
This logs all processes involved in that search. Right down to file access. It will definitely tell us whats happening. 

(And useful info for me, I see some potential to speed up searches with some multi -threading ....)

Davo

**Comment by erik-brangs** [comment] 2020-05-04 15:34
Here's the info for the problematic part:

 ------------ Starting Seach Cycle ----------
Note_Lister : GetNoteDetails totals in Search Mode took 7859mS
Note_Lister : GetNoteDetails CheckID 0mS and Contains 7844mS
Note_Lister : GetContent LoadFile 7582mS and RemXML 48ms and Seach 137mS
Note_Lister : GetNotes : SearchSort 0mS
Search Speed from SearchUnit 7875mS 766mS

And a normal one for comparison:

 ------------ Starting Seach Cycle ----------
Note_Lister : GetNoteDetails totals in Search Mode took 250mS
Note_Lister : GetNoteDetails CheckID 0mS and Contains 250mS
Note_Lister : GetContent LoadFile 63mS and RemXML 31ms and Seach 109mS
Note_Lister : GetNotes : SearchSort 0mS
Search Speed from SearchUnit 250mS 0mS

**Comment by davidbannon** [comment] 2020-05-05 00:35
Hmm, if I did not know you had a new SSD I'd say you have a failing hard disk.  "LoadFile 7582mS" is just a call to lower level FPC library function that loads the note into a data structure.

On a good run, your time spent loading all the notes is about the same as mine, on that bad run, its massive, I don't understand how that can be.

**Some questions ?**
1. How big, in megabytes is your note repository ?  I want some idea of your average note size.
2. How big is your biggest note ?  Its just possible a few really big notes are finding a bug in that library function I mentioned, I'll make some notes that big to test. Just rough numbers in both cases please.
3. Did you have a look at the system monitor to see if you are experiencing unusually large peaks in cpu or disk usage ?

I could avoid that library function I mentioned, (for the record, TStringList.LoadFromFile()) and code up the same behavior in non Object Oriented code, be quite unfashionable to do so.  I would expect such an approach to achieve about the same performance, +/- 20% but at least I could see the low level problems if they exist there. But I would need to be able to reproduce the problem here for that to be useful.  So, any contributing factor you can think of ....

Hmm, I wonder if it would be useful to see a distribution plot of how how long each note took to load when that problem showed up. If only a few (or even one) particular notes take an extraordinary time to load, it might tell me something, but what ?  If I could reproduce the problem here, I would do that but I am conscious of wasting your time.

Davo

**Comment by erik-brangs** [comment] 2020-05-05 06:38
1. Windows Explorer says it has a size of 2,54 MB and 8,71 MB on disk.
2. The biggest note is 36 KB.
3. No, I didn't. Is there any tool that I can or should have running so I can look at it later after the problem has occurred?

**Comment by davidbannon** [comment] 2020-05-05 12:10
[tb-v28e.zip](https://github.com/tomboy-notes/tomboy-ng/files/4580596/tb-v28e.zip)

OK, this one has new code implementing the NoteContains function, to my surprise is substantially faster. In Linux, by a factor of 4, on Windows only 3. (In both cases, Linux is the faster of the two.) Obviously that does not mean it will be immune to the random delay issue but maybe ?  Please test in same manner as previous.

A: I have one note of 38K and several in the high 20's. So my test set is representative of yours. Sigh ...

A: I think from memory that Windows has some built in tools showing resource usage, maybe under Task Manager ?  Not sure, not a regular windows user. I have a mental picture of a rolling chart showing you the last hour or so ?  Just shut down my Window, sorry.

Davo

**Comment by erik-brangs** [comment] 2020-05-05 18:33
I think there's a problem with the search with the version you posted. I'm not getting any results, no matter what search term I use.

**Comment by davidbannon** [comment] 2020-05-06 01:00
[tb-v28f.zip](https://github.com/tomboy-notes/tomboy-ng/files/4584440/tb-v28f.zip)

Oh, I was testing with a term I knew was not present so it did not "short cut". And while doing that, messed up the code and did not go back and test with something present. Sorry.

This works, but does not deliver the massive speedup I was so surprised about, in fact, its maybe 10% to 20% slower.  And that is well within what I would expect.   But the question is, will it solve your problem of the erratic really slow one.

In either model, I think I can speed it it, later !

Davo

**Comment by davidbannon** [comment] 2020-05-09 12:40
Erik, did you get around to testing that 'f' version of v0.28 ?

I have some speed up options for searching but don't want to push them until I know if this helped with the problem you are seeing ....

Davo

**Comment by erik-brangs** [comment] 2020-05-09 15:44
Yes, I tested 0.28f. Unfortunately, search is still very slow sometimes.

I had the task manager open and it didn't look to me like there was any significant parallel load.

**Comment by davidbannon** [comment] 2020-05-10 01:17
Hmm, 0.28f uses file access calls that are quite close to the operating system, I think we have to assume the variations you are seeing are due to caching, while the notes are in the cache, they get delivered a lot faster than if the OS needs to go and get them from the hard disk, that applies even with SSD's, access to the ssd is still a lot slower than access to memory.  Its not that the first one is slow, subsequent ones are faster ! 

I can reproduce the issue on a older version of windows, Vista (yes, I still test against Vista). Its older hardware too of course. With 2000 notes, I see a delay of up to 5 seconds with an average access time of 800mS, if I keep repeating the search, its consistently 800ms but if I load a browser (scary on Vista) and mess a round a bit, go back and do a search, its initially slow again.  That is very typical cache behavior.

Linux on the same hardware was much better.  Interestingly, I find Windows10 on my laptop, ssd and lots of memory appears almost as fast as Linux on same hardware. They are catching up ....

I will push out my SMP searching model in the next release of tomboy-ng, while faster overall, especially on newer hardware, it will not eliminate the variation you are seeing.

David

**Comment by davidbannon** [comment] 2020-06-25 05:33
I would like to say "Fixed in v0.29" but I suspect not.  Its definitly faster now with large note collections and a multicore machine but I don't think that addresses Erik's specific issue. That, I am afraid is just that it does take a certain amount of time to index a large set of notes.

Thanks for the report.

Davo

**Closed by davidbannon** 2020-06-25 05:33 UTC
