### ISSUE TITLE
unwelcome welcome window

### ISSUE THREAD

**Issue by EbStewart** [tomboy-notes/tomboy-ng#116] opened 2019-12-18 16:05 UTC
on windows 10 edu
 I can't get rid of the 'welcome to tomboy-ng' window, not by X-ing out of it nor by minimising it. The other notes disappear if I do. It includes the text:

"Sadly, on this OS or because of a Bad Note, I cannot let you dismiss this window"

How do I find out if its caused by a bad note and how do I then fix it?

![tomboy-ng window bug](https://user-images.githubusercontent.com/52795868/71115995-1bff1100-21cb-11ea-821e-54a298457334.PNG)

**Comment by davidbannon** [comment] 2019-12-18 23:30
Hello Eb, I am afraid the problem is exactly what it says, "Failed to index one or more notes".  It has found an error in your notes and that screen is looking after your valuable data !

Hover the mouse over the error messages and it tells you to go to settings, Snaphots and click Recover. Read the intro screen, take a safety snapshot, click "Existing Notes" tab. If you are sure you don't need the bad note, delete it or double click it to take things further.

I would very much like to know where this bad note came from ?  Are you a new tomboy-ng user, it maybe be an old note. The origional Tomboy just ignored any note it could not read. But if you have been using tomboy-ng before this, it says to me that badnote is new and we'd both like to know how it happened !

Please report back.....

Davo

**Comment by davidbannon** [comment] 2019-12-26 07:12
I have not heard from Ed, problem is in his hands. I will close this ticket now, he should feel free to reopen if he desires.

**Comment by EbStewart** [comment] 2019-12-26 18:48
I did respond, by email, in reply to your email Apparently that doesn't get through to you. Here is the text I sent

"Ok, I did as directed:

> Hover the mouse over the error messages and it tells you to go to settings, Snaphots and click Recover. Read the intro screen, take a safety snapshot, click "Existing Notes" tab. If you are sure you don't need the bad note, delete it or double click it to take things further.
FormRecover window said there was one bad note. I deleted it, but saw, upon fiddling, that there were a number of notes that wouldn't open. Neither would they open from the Search window. So, I made the search window bigger so I cold see the file names, for each unopenable note, opened it with notepad++, made a small change and saved. Some of them became opened, I think but not all of them. (I did it hours ago. Sorry I didn't document anything at the time.)

I did not finish doing the above for all unopenable notes.

In any case, the FormRecover Window says there are no bad notes, the splash window does not show at startup if that box isn't checked, which is different and better, but if it does start with splash, the app crashes when the splash is X-ed closed.

So that is still buggy."

Now I will add a different bug, that one can't cntrl+shift+arrow key (any) to select blocks of text, although cntrl+arrow,shift+arrow (r & L only), home+arrow and end +arrow do work as expected.

**Comment by davidbannon** [comment] 2019-12-26 21:53
Hi Eb, yes, I have noticed that posting to here via an email client does not seem to work.  Git hub claim it does ....
Now, I was under the impression that you, as the originator of this thread could reopen the ticket yourself ? Apparently not ?  

Anyway, sounds like you have more than one bad note. Not sure I quite understand whats happening here. Are you saying that you have more unopenable notes but they are not listed in the recover section ?  How do you know you have more unopenable notes please ?

Can you tell me, step by step, what you do to trigger that crash ?  I have not seen anything like that.  Its complicated by the fact that the newly released V0.25 has substantially rewritten startup code and its quite possible the combination of factors that triggers your crash don't apply any more. 

As a by line Ed, I think its quite important that I 'encourage', strongly, end users to deal with bad notes.  I know several Tomboy users who, when they switched to tomboy-ng found notes they did not realise they had lost. I have a lot of very important data in my notes, scared of loosing any of them !  If you have lots of bad notes, I thing we need to find out why.

**Comment by davidbannon** [comment] 2020-01-03 11:21
Hi Eb, not heard back from you. If you are replying from your email client, that may not work.  I know it does not work for me using Thunderbird.  Please work from the github web interface if you can.
Davo

**Comment by EbStewart** [comment] 2020-01-04 15:14
if the splash screen is displayed, then  closing it crashes program.
settings>snapshot>Recover lost notes says no bad notes, but I don't believe it because some of them won't open.
![image](https://user-images.githubusercontent.com/52795868/71767502-c6ce3980-2f04-11ea-8172-c41f05c8e7a1.png)

**Comment by davidbannon** [comment] 2020-01-04 22:52
OK Eb, thanks for that.  We have two options to deal with this, firstly, if you could start tomboy-ng in debug mode and send me the result. Alternatively, if you could send me one of these notes, I can do it here.  For the first model, because Windows does not write to console, you need to capture that output to a file.
I have tried to capture all the likely problems that might occure in a note but looks like I have missed one. Sigh ...
I will need to boot my laptop into Windows and experiment a bit to get the exact command line you need. Will get back to you later today.

**Comment by davidbannon** [comment] 2020-01-04 23:56
**Create a windows debug file**
1. Rightclick the startbutton and select "run" 
2. In the field, enter this command line exactly as show - 
"C:\Program Files\tomboy-ng\tomboy-ng.exe" --debug-index --debug-log=%userprofile%\Desktop\tomboy-log.txt
3. Press enter, tomboy-ng should start up normally. Close it.
4. A file called tomboy-log.txt will have been created on your desktop, please look through it ensuring no privacy issues (should not be, but lets be careful), attach that file to this github issue thread.

**Comment by EbStewart** [comment] 2020-01-05 14:11
[tomboy-log.txt](https://github.com/tomboy-notes/tomboy-ng/files/4023335/tomboy-log.txt)

I did as directed above after correcting the path to Desktop (%userprofile%\Desktop didn't find it. It's on a separate partition, as is my notes directory.) and in fact repeated it a few times (quitting the app in between), as you'll see in the log. I tried opening one of my bum notes but it didn't log anything except 'left-click'.
In finding the .exe location (funny, I didn't see it in Program Files at first, but I probably just missed it) I read some of the tutorial .NOTE files you have in the directory with the .exe. This pointed me to a possible cause of note badness... My notes are saved to a tresorit (encrypted cloud service) shared directory that is accessed by both my windows and linux Linux Mint (derived from ubuntu) partitions. So this is NOT a sync directory, it is the notes directory. Is there a possible problem with line endings formats?? Other text and word docs have no problem with them, but maybe XML docs do?? or just something else about the notes doesn't like being shared this way? I do it because I don't have to remember to sync. I hadn't even set up a sync directory before today. Now I have and it seems to be working, though I haven't rebooted into linux  yet to check that side.


![image](https://user-images.githubusercontent.com/52795868/71779911-5500f900-2fb3-11ea-8f1f-d462f7833ef0.png)

This could have nothing to do with my problems at all. They could stem from farting around with my Tomboy notes, screwing up their manifest file and then importing them into tomboy-ng...

I'm going through and deleting bum notes. what happens with these iis that they just don't open when clicked on. The app doesn't crash, just nothing happens. tomboy-ng doesn't recognize that there are bad notes.

**Comment by EbStewart** [comment] 2020-01-05 14:15
when I say accessed, I mean that both OSs have a directory in their file manager that are synced through Tresorit. I would have thought that that took care of file endings.

**Comment by EbStewart** [comment] 2020-01-05 14:27
BTW, the way I've been rescueing my unresponsive notes is to click 'Recover Snapshot' then double click a recent Snapshot so that the notes in it appear in the right pane titled 'Notes in Snapshot 'date time'. Once I can see the name of the note and its hex filename, I can find that file in the file manager, open it with Notepad++ copy the important bits into a new note and then delete the bad note. This is a bit time consuming and somewhat frought as I must be careful not to accidentally click 'Recover'. Yet this seems to be the only way to find the filename of a note from its name. A 'find note filename' or 'view note in text editor' button under an 'advanced' tab might be a good feature to implement for occasions such as this.

![image](https://user-images.githubusercontent.com/52795868/71781498-8257a200-2fc7-11ea-8a26-a0407f557c23.png)

**Comment by EbStewart** [comment] 2020-01-05 14:30
also you can't resize column widths in the above screenshotted table (screenshat? screenshyte? what is the past tense of screenshot?) which would be useful in a minor way.

**Comment by EbStewart** [comment] 2020-01-05 15:04
ok, I've deleted all notes that didn't open and still when I click the X in the right top corner of the splashscreen window it crashes the app.

**Comment by davidbannon** [comment] 2020-01-05 21:34
Eb, the x in the right top corner is intended to close but not crash the app. Are you sure you are seeing a crash ?

Hmm, both Tomboy and tomboy-ng are (should be) indifferent to line endings.  And I guess the encryption your file service offers does not change the note.  But sharing a note between multiple installs without using the sync system is risky.  If there is any chance that the note directory can be accessed by two systems at the same time, DANGER Will Robertson Danger !  You might be OK if you can be absolutely sure only one system is powered up at at a time, such as a dual boot machine but if you also use Tomboy in the mix, I would strongly not recommend it, I do not understand Tomboy's indexing mech, it may not be OK.

If you don't mind, I would really like to see one of those dud notes. Identifying the problem might let me make -ng be able to deal with what ever has happened.

We need to work togeter on a past tense for screenshot, agree its needed ..... carefully !

Eb, you are using v0.24 of tomboy-ng, right ?  v0.25 has a quite different approach to that small screen, lots of changes that affect mainly Linux users but the changes are there in all systems. It could be that the problem you are experiencing has been unintentionally 'fixed'  with  that rewrite. Please update and test.

Else, I need to build you a special version that has a whole lot of extra debug stuff especially around the closing process.

**Comment by EbStewart** [comment] 2020-01-06 01:20
![image](https://user-images.githubusercontent.com/52795868/71789026-e7d77d00-301f-11ea-97f4-3c48bae910f7.png)

**Comment by EbStewart** [comment] 2020-01-06 01:24
I can't paste in the notes, even though I told windows they open with notepad++, so I'll open them with that and paste in the text:
<?xml version="1.0" encoding="utf-8"?>
<note version="0.3" xmlns:link="http://beatniksoftware.com/tomboy/link" xmlns:size="http://beatniksoftware.com/tomboy/size" xmlns="http://beatniksoftware.com/tomboy">
  <title>Fowler on bloated Domain Objects vs. duplication of usage specific behaviour</title>
  <text xml:space="preserve"><note-content version="0.1">Fowler on bloated Domain Objects vs. duplication of usage specific behaviour

A common concern with domain logic is bloated domain objects. As you build a screen to manipulate orders
you'll notice that some of the order behavior is only needed only for it. If you put these responsibilities on the
order, the risk is that the Order class will become too big because it's full of responsibilities that are only used
in a single use case. This concern leads people to consider whether some responsibility is general, in which
case it should sit in the order class, or specific, in which case it should sit in some usage-specific class, which
might be a Transaction Script (110) or perhaps the presentation itself.

The problem with separating usage-specific behavior is that it can lead to duplication. Behavior that is
separated from the order is harder to find, so people tend to not see it and duplicate it instead. Duplication can
quickly lead to more complexity and inconsistency, but I've found that bloating occurs much less frequently
than predicted. If it does occur, it's relatively easy to see and not difficult to fix. My advice is not to separate
usage-specific behavior. Put it all in the object that's the natural fit. Fix the bloating when, and if, it becomes a
problem.
p.113</note-content></text>
  <last-change-date>2019-07-27T23:02:06.5878685+01:00</last-change-date>
  <last-metadata-change-date>2019-07-27T23:02:06.5878685+01:00</last-metadata-change-date>
  <create-date>2019-07-27T23:00:25.7535630+01:00</create-date>
  <cursor-position>1</cursor-position>
  <selection-bound-position>1</selection-bound-position>
  <width>450</width>
  <height>360</height>
  <x>2128</x>
  <y>551</y>
  <open-on-startup>True</open-on-startup>
</note>


<?xml version="1.0" encoding="utf-8"?>
<note version="0.3" xmlns:link="http://beatniksoftware.com/tomboy/link" xmlns:size="http://beatniksoftware.com/tomboy/size" xmlns="http://beatniksoftware.com/tomboy">
  <title>Convention Over Configuration</title>
  <text xml:space="preserve"><note-content version="0.1">Convention Over Configuration

most often defined as a software paradigm 
where the amount of decisions that a developer must make is minimised. this is at a risk of loss of flexibility, i.e. ease of implementation of alternate design choices not accounted for by the convention... configurations defined by the developer.

I think it means the system conforming to certain conventions in order to allow certain automatic processes to proceed, thereby avoiding explicit coding of, for example, a link between a class and the DB table it should correspond to. So if the two names meet the format prescribed by the convention, the linking happens automatically.
for example, naming conventions to allow automatic linking of 'class Sale' to table 'sales'

the downside is that often implementation of this makes it harder for devs to write code that doesn't conform to the conventions prescribed.

(<italic>An Investigation of Data Flow Patterns Impact on Maintainability When Implementing Additional Functionality</italic>)

For this approach to be followed, the developer must know the frameworks conventions.

pluses are ease of development, more consistent more easily maintainable code and less need for configuration files.</note-content></text>
  <last-change-date>2019-03-24T23:41:24.1373513+00:00</last-change-date>
  <last-metadata-change-date>2019-03-24T23:41:24.1373513+00:00</last-metadata-change-date>
  <create-date>2019-03-24T20:47:39.0819758+00:00</create-date>
  <cursor-position>1</cursor-position>
  <selection-bound-position>1</selection-bound-position>
  <width>980</width>
  <height>663</height>
  <x>2734</x>
  <y>357</y>
  <open-on-startup>True</open-on-startup>
</note>


<?xml version="1.0" encoding="utf-8"?>
<note version="0.3" xmlns:link="http://beatniksoftware.com/tomboy/link" xmlns:size="http://beatniksoftware.com/tomboy/size" xmlns="http://beatniksoftware.com/tomboy">
  <title>WCF</title>
  <text xml:space="preserve"><note-content version="0.1">WCF
(Windows Communication Foundation)

Microsoft proprietary tech

based on/built on? SOA: four tenets:

1. boundaries are explicit. this is about universal deployment of services. messages must be able to cross any boundary so service are not bound by environment or language.
attribute based programming enables definition of 'external service contracts'. If not explicitly defined, there can't be explicit exposing of functionality.

2. Autonomy of Services Services are manages and versioned independently of each other - inner workings are hidden from each other. Contract is interface.

3. shared schema and contract. Rather than classes &amp; types. These used by clients to generate own code to call the service - Loosely Coupled system. With schemas and contracts, inner workings of code not needed to pass data.

4. Services interact by looking at each others' policies for compatibilities that will enable interaction.</note-content></text>
  <last-change-date>2019-03-06T15:14:51.4802734+00:00</last-change-date>
  <last-metadata-change-date>2019-03-12T10:38:15.8955418+00:00</last-metadata-change-date>
  <create-date>2019-03-06T14:53:21.8592591+00:00</create-date>
  <cursor-position>1</cursor-position>
  <selection-bound-position>1</selection-bound-position>
  <width>450</width>
  <height>360</height>
  <x>1449</x>
  <y>1059</y>
  <open-on-startup>True</open-on-startup>
</note>


if this method of transmission isn't good for you, you'll need to give me an email address I can send them to as attachments? or you tell me a way that'll work.

**Comment by EbStewart** [comment] 2020-01-06 01:38
okay, I pulled these notes out of the bin. Github said I couldn't  copy and padste them into its window and the markup was stripped out when I tried pasting the text I got from opening them in Notepad++, so here they are zipped:

[bum notes.zip](https://github.com/tomboy-notes/tomboy-ng/files/4024369/bum.notes.zip)

I told windows to open them with Notepad++ in their properties, in hopes I could then drag the files into this github window. If that changes them in ways you'd rather it didn't, I can send others

**Comment by davidbannon** [comment] 2020-01-06 10:31
OK Eb, that is really very strange. I can open all three of those note without problem. One of them apparently had had its extension changed, it was .xml rather than .note so I had to rename that one. Otherwise, -ng would totally ignore it.  I cannot imaging how that initial rename happened ...

But the real issue is the other two, your system was not picking those notes up, neither complaining they were broken nor reading them. But they were in your normal notes directory ?  I don't quite follow what you did to them with notepad++, maybe its worth sending me another one that has just been zipped ?

I also tried clicking the X, top right, while looking at each of these notes, normal, crash-less  exit.

Davo

**Comment by EbStewart** [comment] 2020-01-06 14:24
ok. the extension change is probably down to me fiddling around trying to open that note up to copy out the text. Anyway, I looked in my recycle bin for notes to send you. They all had a notepad++ icon because I changed properties>>opens with: to notepad++. Now I've changed them all back to open with tomboy-ng so hopefully we're back where we started.

![image](https://user-images.githubusercontent.com/52795868/71823044-4a676200-308e-11ea-97e7-fc2f3a16979b.png)

here are three more notes which I've pulled out of the recycle bin. They do not open when I click on them on the desktop. I put one of them in the notes directory and it still didn't open. here they are all zipped up.

So are you saying that clicking the top right corners X in the slash window is SUPPOSED to quit the whole program?That seems like an odd way for it to work. Surely it should only close that one window? Whether that engenders a crash or a graceful exit, it seems broken to me. I look to close the app by left clicking the icon in the system tray and choosing quit. I'd like to be able to close that little splash window without making all of the notes I have open disappear too.

**Comment by EbStewart** [comment] 2020-01-06 17:56
Oookaaay, I've just realised that I can dismiss the splash window without closing the entire app  by  clicking the ... wait for it... Dismiss button. That is still counterintuitive IMHO. The X should close just that one window and if you want to make it easy to close the app from that window, make that button do that and label it 'close the app' or 'Quit' or something clearly descriptive.

**Comment by davidbannon** [comment] 2020-01-07 11:16
Yep, you have it Eb, the little splash screen is actually the apps main window and while some OS's let me capture and override a click there, some do not.  So, for consistency, I allow it do do its job.  Maybe that needs some more work...

Eb, when you put that dodgy note back in the tomboy-ng note directory, did you restart ir refresh the note list ?  tomboy-ng won't notice it there otherwise.

I am afraid I cannot see the zip file you sent me ....

Davo

**Comment by EbStewart** [comment] 2020-01-11 19:04
1. Here is the zip file again

[more bum notes.zip](https://github.com/tomboy-notes/tomboy-ng/files/4049447/more.bum.notes.zip)

2. I extracted this zip, then, with tb-ng not running, in file manager clicked on one of them with no visible result. Here is that note opened with notepad++

![image](https://user-images.githubusercontent.com/52795868/72206295-ca713b80-3483-11ea-941a-1f0dc949643b.png)

I say no VISIBLE result because I was then unable to open an instance of tb-ng.

![image](https://user-images.githubusercontent.com/52795868/72206366-b11cbf00-3484-11ea-961f-97e0ab338e99.png)

so I had a look at the windows task manager to see which processes were running and found that note I'd clicked on running

![image](https://user-images.githubusercontent.com/52795868/72206378-05c03a00-3485-11ea-8234-003838852b9a.png)

So I killed that process, copied that note into the notes directory and started tb-ng and got the splash window with a bad note warning

![image](https://user-images.githubusercontent.com/52795868/72206432-ba5a5b80-3485-11ea-8dbd-6b3585d5cabb.png)

So I went to Settings>Snapshot>Recover Lost Notes>Existing Notes and got that note listed in the Form Recover window, so I double clicked on  it as instructed

![image](https://user-images.githubusercontent.com/52795868/72206483-5f753400-3486-11ea-9780-82d4c2961a53.png)

so I aborted. Then tried again to open tb-ng. I repeated all steps with the same results up until I 'got that note listed in the Form Recover window, so I double clicked on  it as instructed'. This time A note was displayed

![buggy Note recovery attempt](https://user-images.githubusercontent.com/52795868/72206589-95ff7e80-3487-11ea-912c-e97bdc8a68c7.PNG)

2. leading in to 3.  Very curious, I thought. So I again closed the program and re-opened. I repeated the steps again with the same result as last time. So I removed the note from the note directory in the file manager. But before restarting clicked on the system tray icon and saw a note that looked like it.  I opened it up, it was actually a different note that belonged in my network Applications CW1 notebook, so I filed it there using the icon at the top of the window. Then I decided to see if it showed up in the search window. So I opened the search window from the system tray, and clicked on my network Applications CW1 notebook. The newly added note was there, but three notes I had put in there before performing the above described experiment, were not there, which is bad. In fact, all of my other notebooks were empty, which is very bad. If I clear filters, they all appear in the right pane of the search window, but of the notes I've checked, none of them have notebooks assigned to them (menu bar of note>notebook icon>existing notebooks) all the checkboxes were blank.

So remembering that I had not properly closed the app after deleting the bum note, I closed and reopened the app and found that the newly added note had also disappeared from the network Applications CW1 notebook! Now all of the notebooks I created are empty and no notes have notebooks assigned to them. The notes are still there though.

Any suggestions?

4. I liked Tomboy because I could navigate from note to associated note by clicking on a note name within the selected note and immediately I was there. those links were easy to differentiate from surrounding text and it was I didn't need to select them then press a button at the top. Now I link names look just like the rest of the text making it a guessing game and I can't just click and I'm there. I liked the way the old Tomboy functioned better.

**Comment by EbStewart** [comment] 2020-01-11 19:11
edit of above:

> I say no VISIBLE result because I was then unable to open an instance of tb-ng.

please make that 'beacuse after quitting the app, I was then unable...

**Comment by dajoker** [comment] 2020-01-11 19:20
@EbStewart the notebook reference loss is new, and fixed for the next release:  https://github.com/tomboy-notes/tomboy-ng/issues/128

**Comment by davidbannon** [comment] 2020-01-11 21:20
Eb, sorry, once again I had no problems opening those three new notes. Once again, all I did was unzip and double click on each note, one by one.
Now, that double click is what I call "single note mode", it opens a note out of the tomboy env.  It works on my machine because I have 'associated' *.note with tomboy-ng.  I don't think the Windows installer does that so its necessary to tell Windows that when you click on *.note, you should open it with tomboy-ng. Maybe a right click and "open with" can confirm that ?

As to why adding those notes to tomboy-ng's note directory not allowing you to see them, again, I am puzzled indeed. When I get home later today, I will open up a Windows session and try that exercise there. 

Do be aware that the "recover lost notes" facility cannot help if there is no content left in the note, its just a fragment of XML. Then all you can do is delete the note. Click a note that you are sure is dead and the Delete Button becomes available, easier and less error prone than searching for it in your File Manager.

I see you are still using V0.24.

Davo

**Comment by davidbannon** [comment] 2020-01-12 12:33
OK, maybe I have identified what you are seeing Eb?
Some tests on Windows with those notes of yours. It looks like Windows does not force a new windows to appear in the normal screen area like Linux/Mac do.  Those notes had very high 'Left' settings, some 2600 pixels. Probably because they were last saved on a system with a high resolution screen. That means that if they are subsequently opened  on a lower resolution screen, on Windows, they appear to the right of the right hand edge of the screen. That is, obviously, not appearing at all !

I have added a check that some part of a note is always visible at startup.

I need to do some tests and will try and get a new release out with that fix (and others) asap.

Davo

**Comment by davidbannon** [comment] 2020-01-12 12:46
One more thing, you mention that links are not showing up in Blue ?  I suspect that because you are using it in SingleNoteMode, it does not make sense to honour links when you are probably editing a note that is not in your regular notes directory. 
Its all as you expect if you work in the normal Tomboy way.
Davo

**Comment by EbStewart** [comment] 2020-01-12 20:23
> Maybe a right click and "open with" can confirm that ?

Did that, it didn't open with the tomboy-ng app.  The notes have the correct green icon though, so I think they are associated.
attempting to open that bum note started a process though, but not a normal tb-ng one as there is no tray icon. see image below 

![image](https://user-images.githubusercontent.com/52795868/72225086-31245100-3579-11ea-9bd3-76e6b9035193.png)

I was unable to open the app normally until I killed the process in task manager.

> Do be aware that the "recover lost notes" facility cannot help if there is no content left in the note, its just a fragment of XML.
the first image in my last post shows that note opened in notepad++. There is clearly some content there.


> OK, maybe I have identified what you are seeing Eb?
> Some tests on Windows with those notes of yours. It looks like Windows does not force a new windows to appear in the normal screen area like Linux/Mac do. Those notes had very high 'Left' settings, some 2600 pixels. Probably because they were last saved on a system with a high resolution screen. That means that if they are subsequently opened on a lower resolution screen, on Windows, they appear to the right of the right hand edge of the screen. That is, obviously, not appearing at all !

But since I started this bug thread, I have only used the app on Windows 10 Edu. In any case, my linux and windows partitions are on the same machine with more or less the same screen resolution set, so I don't think that that's it.

**Comment by davidbannon** [comment] 2020-01-13 01:14
Hmm, there is a difference in the way Windows and Linux scale high resolution screens.  In my case, for example, the small splash screen is about 50% wider and higher on Windows than on Linux, same hardware.  This means that windows reports to LCL a different screen width.

I have just tested the changes I made and now, a note editing window that wants to appear beyond the screen always has a corner within the screen, that corner appears lower right.  I think it could be further in but not sure, maybe someone really does want it tucked off near the side ?

Anyway, no issues opening those three notes in Windows now.

Anyway, that fixes the only problem I can replicate at this stage. I suggest it might be worthwhile you trying it Eb ?

Davo

**Comment by EbStewart** [comment] 2020-01-13 17:28
ok, I uninstalled the version of the app I had and installed v0.25.
as far as I can see all of my issues are solved

**Comment by davidbannon** [comment] 2020-01-13 23:01
No, sorry Eb, not all issues I am afraid.  In 0.25 notes still forget about their notebooks.  I am rushing out a newer release as fast as I can but fixing that has lead to some other issues. I think I am on top of them now, will do some aggressive testing and if all is well, replace the binaries in 0.25 with something like 0.25f - sooner rather than later !
Davo

**Comment by EbStewart** [comment] 2020-01-15 21:24
Hmm. I've just upgraded to v0.25 and waas planning on going up to 0.26, but since I'm still getting all of the posts by email, I'm thinking wait a while?

**Comment by davidbannon** [comment] 2020-01-16 00:13
Eb, 0.25 will be fine as long as you don't use Notebooks.  But it will definitely forget what notes belongs to a notebook as you open them.
I need to add the windows version to the 0.26 release and cannot do that now, am away from home.  About 36 hours. Then, yes, I suggest you do upgrade to 0.26. Its been a lot more rushed than I like but I think its safer than 0.25.  Sorry !
Davo

**Comment by EbStewart** [comment] 2020-01-17 03:06
no problem. Thanks for all the hard work. Gokurosama, in Japanese.

**Comment by davidbannon** [comment] 2020-01-18 00:04
OK Eb, windows version available again. Its now version 0.26a.
-----
Backstory is a one line windows only patch that deals with the fact that windows cannot 'move' a file over top of an existing file. To minimize the possibilities of (eg) power failure happening just as we write a note to disk, I write it out as a temp file and then move it on top of the file its replacing. In Windows I have to delete the target file first, reducing slightly the advantage gained. Still valuable, especially on a non-journal files system.

Ever since I said in the v0.25 announcement email I think its time I called it Version 1.0, I have been plagued by instability. Hope we are there now. Sigh .....

Davo

**Comment by EbStewart** [comment] 2020-02-06 13:18
I've been away for awhile...

I'm on version .24b on linux mint and it seems stable except for notebooks
is the latest version stable and are notebooks working?

**Comment by dajoker** [comment] 2020-02-06 13:38
0.26 seems stable to me (openSUSE x86_64, KDE, non-Qt version) and notebooks work there, yes.

**Comment by EbStewart** [comment] 2020-02-06 14:09
ok thanks

**Closed** 2020-02-06 14:09 UTC

**Comment by davidbannon** [comment] 2020-02-07 11:07
Eb, that issue you noted about pasting text at the very end of a note is still there in 0.26

Sorry.

Davo

**Comment by alexanderadam** [comment] 2020-05-15 08:06
I just ran into this error because I imported some tomboy notes.
Around sixty of the older tomboy notes have the issue that they miss a closing `</note>` tag and a closing `</text>` tag.

For instance:

```xml
<?xml version="1.0"?>
<note version="0.3" xmlns:link="http://beatniksoftware.com/tomboy/link" xmlns:size="http://beatniksoftware.com/tomboy/size" xmlns="http://beatniksoftware.com/tomboy"><title>Foo bar</title><text xml:space="preserve"><note-content version="0.1" xmlns:link="http://beatniksoftware.com/tomboy/link" xmlns:size="http://beatniksoftware.com/tomboy/size">Foo bar


<list><list-item dir="ltr">baz</list-item></list>
</note-content>
  <last-change-date>2020-05-15T09:32:05.8670000+02:00</last-change-date>
```

Somehow they are working fine in (original) tomboy, though.
