### ISSUE TITLE
Improve performance for large note collections (preventing lags and loss of access for seconds at scale)

### ISSUE THREAD

**Issue by mlncn** [tomboy-notes/tomboy-ng#29] opened 2018-02-04 20:04 UTC
Some apologies for [dragging this over from old Tomboy](https://github.com/tomboy-notes/tomboy/issues/54), but i'm hoping the next generation can keep scaling issues in mind!

Instead of very long lags at specific points (creating a new note, naming/renaming) as in my old (very old) Tomboy, Tomboy NG is more spread out in its slowness.  Compared to my old Tomboy, it's faster to start up, infinitely faster to create a new note, seems a little faster to rename notes, and maybe faster to search.  However, it is slower at some more regular/constant use things.

Most frustratingly, it will often not show text as i type it, but need two to three seconds to catch up.

My prescription for solving these problems is the same.  Moving notes from XML to a database is not needed to address these user-perceived performance problems.

1.  Keeping all user interfaces response processing (showing characters as one types, creating a new note, changing the title of a note) in one dedicated process/core, while moving all expensive operations (finding existing titles that match text typed into a note, searching through other notes for text to link to a new note or changed title) to background processes.
2.  Using indexes.

The indexes could indeed be implemented with SQLite or another database rather than flat files, but the notes themselves i think can stay as XML files while still scaling the performance of the application.

Software & Hardware Environment and Circumstances:

- 16,722 notes totaling 150M.
- Seven notebooks (most notes unaffiliated with a notebook).
- v0.12 of tomboy-ng. Build date 2018/01/31 TargetCPU x86_64 OS Linux.
- SSD hard drive.
- 16GB RAM.
- Intel Core i5-2540M CPU @ 2.60GHz x 2.
- Mint Debian Edition 2 Cinnamon.

**Comment by davidbannon** [comment] 2018-02-04 22:52
Yep, no doubt you have that right Benjamin !
I do have some experimental code that resets a timer every time you type something. If the timer does, in fact, time out, its because you are having a think and I can then dive in and do the housekeeping. I was a little disappointed in the level of improvement it delivered however. As a matter of interest, try turning off "display links" from the settings form. That might give you some idea of the improvement possible. The rest of the delay, if any, is right there in KMemo, and I'm afraid thats a black box.
I do most of my development (and other stuff) on a i3 celeron, spinning disk and 4gRam so a lot less of a machine than you are using. But I don't use or even like the links popping up so run with them off all the time and like that, its fine. 
I'll look further into that experimental code. Git will find a way back for me if needed.
**Indexes** - I keep a data structure in RAM with the names and IDs of all notes (not the content). That should allow me to check words for links quite fast, any saving delivered by a database would be at startup only. So I don't think that would help with your immediate problem.
Mind you, I have only tested with my 200 odd notes, not your 16K. So, maybe its time I looked at how I search that internal list ?  Right now its just a for loop asking each time does something match something. A BTree or whatever could help there too.

**Comment by mlncn** [comment] 2018-02-12 22:17
I think keeping the data structure of all notes in RAM is not going to scale for my needs (although i am looking for a computer which supports at least 32GB RAM to replace my seven year old machine...)

So i should disable "Show Internal Links" ?

Yes, if i turn that off there's an immediate improvement, showing text as i type it initially, but pretty quickly it reverted to high CPU usage and delay.  Typing the below at about 50 words per minute it showed about the first 50 characters i typed, but then took 15-20 seconds to show the rest.

So there's definitely an improvement if it's not trying to show internal links (and i wouldn't want these to not be shown at all, but i'd be fine if it only did it when opening a note or when manually requested, though personally i like the serendipity of immediately learning when i'm referencing a person, place, or topic i already have a whole note about!)

But it seems there's something else slowing trying to consult or just keep that memory alive that significantly slows Tomboy NG in regular usage (typing in an existing note, pasting in text into a new note).

**Comment by davidbannon** [comment] 2018-02-12 23:28
Hmm, with Links off the other housekeeping things are pretty quick. And you are running a pretty gutsy machine. I suspect any delays we are seeing now are the underlying KMemo component, thats really a black box. At some stage it may be appropriate to go back there and do some profiling and see if the author is interested in removing some aspects, making a stripped down version but I am not overly confident that will work.
I do find performance on my slowish laptop acceptable. On an old Atom powered netbook, I must turn off links and even then its painful to use. But so is Tomboy ....
One problem is I cannot, in my wildest dreams, type at 50wpm ...
D

**Comment by davidbannon** [comment] 2018-02-18 06:25
OK, I have checked in code that sets or resets a timer every time the user makes a change. Thats set to 4 seconds right now and I thinks thats a bit disconcerting so I think its going to need some experimenting to determine a good value. Similarly, another one controls the autosave at 10 seconds. Its now setup to also be restarted when a user types something. But it does deliver an improved responsiveness, not a huge change but a worthwhile one. 3ce5f08
I can still saturate a core on my laptop typing quickly.

**Comment by kernelOfTruth** [comment] 2018-04-27 14:41
@davidbannon thanks for your work !

I also got quite a note collection, carried it over to gnote (cherrytree had issues with import so would have to be imported manually)

and it usually takes 30 seconds or several minutes to open a new note, edit & search files

tomboy was way faster with recent mono releases, got almost no lags.

Unfortunately support/maintainership got ended on Gentoo

Looking forward to trying out tomboy-ng in the near future

**Comment by davidbannon** [comment] 2018-04-27 23:44
Hi kernel, v0.14 is faster than previous but the improvements are mainly in around indexing and searching rather than opening. I am not happy wih speed to -ng when editing a large not in particular and rather fear there may not be anything I can do about that. So, be interesting to hear your feedback.
If you don't already have gtk libaries installed, you will need them, I not had much to do with Gentoo for a long time so, again, your feed back ....

**Comment by kernelOfTruth** [comment] 2018-04-28 22:15
@davidbannon performance appears to be speeding fast,

searching works really quickly in a few moments,

haven't tried editing, etc. so far yet.

I've only copied a rather big note from gnote to tomboy-ng and it was instantly there (so far formatting doesn't work)

on gnote this takes ages (30 seconds to several minutes usually)

**Comment by erik-brangs** [comment] 2018-10-04 15:14
For my note collection (~ 1800 notes), search is very fast on Linux with 0.18b (feels like the results appear instantly). However, on Windows, searches always lead to a lockup for a few seconds when searching for a term for the first time. Subsequent searches on Windows are fast enough.

**Comment by davidbannon** [comment] 2018-10-05 01:35
Hmm, I wonder why ? Honestly, I have not done a lot performance testing on windows, just assumed what worked well on Linu would also work well on Win/Mac. A bad assumption.

I'll see if I can mock up a windows test rig when I get home again. Don't have one right now, traveling in Canada....
Davo

**Comment by davidbannon** [comment] 2018-12-13 03:16
I have not been able to reproduce this to be honest. One problem I have is that the only windows platform I have access to is a fairly gutsy desktop with a everything on an SSD so differences in first and subsequent searches is imperceptible. And only about 200 notes.

Just to clarify, by 'subsequent searches' you mean a second search for a different term ?
If so, I have to assume what we are seeing is just windows initial read of the relevant files, after the first search, they are all in the disk cache and so much faster. Maybe a fast computer with lots of memory but a relatively slow hard disk, or a hard disk sharing a channel with some other slow hardware (such as a CDRom drive) ?   

Davo

**Comment by erik-brangs** [comment] 2018-12-13 20:07
Yes,  by 'subsequent searches' I mean a second search for a different term. 

For me, the first search on Windows on a SSD is slower than on Linux on a normal HDD. I'm using version 0.19. I'm seeing similar lockups (tomboy-ng doesn't react for a few seconds) when doing a sync on Windows. For searches, lockups also seem to occur for the first search after I haven't used the computer for a while.

**Comment by davidbannon** [comment] 2018-12-14 06:52
Yes, I'm afraid that sounds like disk access time to me. To search the notes, they need to be read from disk, once read, they will remain in the disk cache for a while so second and subsequent searches will be faster.  I'd expect an SSD to be quicker than you describe but I guess we have to assume thats how it is. The sync operation is similar so not surprising to see same problem.  Do you see the same thing as tomboy-ng first opens up ? We read the same notes then too.

I could, perhaps, make up a special version that records some numbers of the various aspects of that search if you are interested  in that level of debugging ?  It might reveal something we can fine tune ....

How big is your notes dir ?  (on linux, if in default dir   du -sh ~/.local/share/tomboy-ng <enter> )
Davo

**Comment by erik-brangs** [comment] 2018-12-14 07:32
Yes, there's also a delay when opening up tomboy-ng for the first time. My notes dir is 8,5 MB.

I suppose I could investigate where there are any disk optimziations that could be done on the SSD.

**Comment by davidbannon** [comment] 2019-10-15 11:06
Erik, probably time I closed this issue.
I have tweaked the way it works about as far as I can to speed things up. I believe tomboy-ng is quite a lot faster than Tomboy in a number of aspects.
Thanks for your input.

**Closed by davidbannon** 2019-10-15 11:06 UTC
