### ISSUE TITLE
Add sorting of notebooks in NoteBookPick

### ISSUE THREAD

**Issue by frederickjh** [tomboy-notes/tomboy-ng#224] opened 2021-02-01 13:48 UTC
Hi!
This is similar to #192, except this is for when one is editing which notebook(s) that a TomBoy-NG note belongs to. These are still not sorted nor is it possible to sort them.

![image](https://user-images.githubusercontent.com/864159/106466990-55144680-649c-11eb-9f8c-68a03cb2196f.png)

Thanks for considering this enhancement!
Frederick

**Comment by davidbannon** [comment] 2021-02-02 07:35
Thanks for your suggestion Frederick, you sure seem to have a lot of note books !
I will probably be able to do this but not for the forthcoming release, sorry but we have well and truly entered the Feature Freeze time for v0.32. So, look for it in the next release in a few months or, possibly, a beta release a bit sooner.
Davo

**Comment by frederickjh** [comment] 2021-02-02 14:22
@davidbannon and that is not all of them as you can tell from the scrollbar the list goes much further down. No rush I understand the development process. Just happy to help as I can.

**Comment by davidbannon** [comment] 2021-02-24 06:23
OK, this issue is fixed in version 0.32b, will close.  
Thanks for the report.
Davo

**Comment by frederickjh** [comment] 2021-03-22 19:15
@davidbannon I have found one issue with the sorting of notebooks. I added a new notebook today and it was at the bottom. I thought maybe closing and reopening would sort the notebooks but the new notebook name was at the bottom and would not sort there alphabetically.

**Comment by davidbannon** [comment] 2021-03-22 23:15
Hmm, thats curious indeed.  When I add a new notebook it appears, immediately, exactly where I expect it to.

Tell me Frederick, what did you call this new note ?  In particular, is the first character of the name an extended character ?  Not one of the old ASCII characters ?    The reason I ask is that the sorting algorithms put such characters at the end of a list.  For example, I would expect 'ä' to be listed around 'a', either immediately ahead or immediately after, but no, its listed down beyond 'z'.  Apparently characters are sorted according to their numerical value, there are, of course, a huge number of such "non-ascii" characters and a rule set that groups them according to appearance is not practical.

Otherwise, I am quite puzzled. Could you please send me a step by step list of what you are doing so I can try to reproduce it ?

Davo

**Comment by frederickjh** [comment] 2021-03-23 07:27
@davidbannon Sorry, I should have checked better and been  more clear where the sorting is not working correctly. In the left search sidebar on the main window it is working correctly. The new notebook I created is **gpg**. You can see in this screenshot it sorts correctly. Also note that whether the first letter is a capital or not they sort together.

![image](https://user-images.githubusercontent.com/864159/112107866-cb394d80-8baf-11eb-9486-4f976a1be9fe.png)

However if I open a note then click on the **Manage Notebooks** button this is where the new notebook **gpg** is at the bottom. You will also note that notebooks starting with capital letters are sorted together at the top, followed by the notebooks starting with small letters sorted, then the new notebook.

![image](https://user-images.githubusercontent.com/864159/112108453-819d3280-8bb0-11eb-918a-ad0f520332fe.png)

All I know that I did was create a new notebook that starts with a small letter.
To test I created a new notebook **test**. This too was added to the bottom.

![image](https://user-images.githubusercontent.com/864159/112108860-14d66800-8bb1-11eb-850f-07e9baed6776.png)

I then created a new group **Testing**. Both appear at the bottom of the list.

![image](https://user-images.githubusercontent.com/864159/112109026-523af580-8bb1-11eb-8332-1a6af0417565.png)

To be clear these last partial screenshots were also from the **NoteBookPick** window.

I hope this helps!
Frederick

**Comment by davidbannon** [comment] 2021-07-22 07:41
OK, fixed in version 0.33a, thanks for the report.
Davo

**Closed by davidbannon** 2021-07-22 07:41 UTC
