### ISSUE TITLE
Access violation syncing without write permission

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#72] opened 2018-08-17 12:12 UTC
Tested the sync between users. The second user was able to import from a shared directory after 'chwon user1.user2 /media/shared/Notes/':

<Set Files Sync Repo> FormSync shows

```
Could not find local manifest, thats OK
Remote Repo is /media/shared/Notes/
There is a Repo there already, suggest we join it.
2 notes were dealt with.
```

Clicking <Save and Sync>

```
Remote Repo is /media/shared/Notes/
Wow, DoSync appears to be happy
2 notes were dealt with.
```

Good work! Closing the window and back at the welcome screen it still
shows 'Found 0 notes'. Confusing, could be updated?

- Opening tomboy-ng again with the user user does not sync on start.
  Clicking "Synchronize":

```
Found local manifest, good !
Sync completed.
1 notes were dealt with.
```

In the left column:
`Error File Not Found F9FA8E76-E013-4202-A67C-3C351AE66FF7`
Can I dismiss dismiss message it or what to do with it?

Seems I forgot to sync after creating a new note with the second user
(please automate this). Restarting for user2:

```
$ ssh -X user2@localhost tomboy-ng --debug-sync --debug-index
Empty Lists created
Looking for notes in [/home/user2/.local/share/tomboy-ng/]
Checking note [E5855651-DBD1-4532-9FAE-B4BD559CBFEE.note]
Title is [Index]
Checking note [40E7242E-3F1D-4800-947C-B255B217A853.note]
Title is [usage test]
Checking note
[44D8DA9F-B918-45ED-8A44-6BDF06F84B55.note]                                                       
Title is [releases]
Finished indexing notes
```

MainForm shows `Found 3 notes`. Good!

<Synchronize> opens this:

> Access violation.
> Press OK to ignore and risk data corruption.
> Press Abort to kill the program.

```
Backup Dir Checked
TB_Sync - Lists Cleared
TB_Sync - ReadRemoteManifest Done
TB_Sync - ReadLocalManifest Done
TB_Sync - GetListLocalNotes Done
TB_Sync - ManifestList Created Done
Local sync E5855651-DBD1-4532-9FAE-B4BD559CBFEE
In both manifests R=2018-08-17T12:58:21.9080000+02:00
L=2018-08-17T12:58:21.9080000+02:00 Local sync
40E7242E-3F1D-4800-947C-B255B217A853 ERROR - Cannot make rev dir
at /media/shared/Notes/0/2 TESTUP
copy/home/user2/.local/share/tomboy-ng/40E7242E-3F1D-4800-947C-B255B217A853.note/media/shared/Notes/0/2/40E7242E-3F1D-4800-947C-B255B217A853.note
Local sync 44D8DA9F-B918-45ED-8A44-6BDF06F84B55 In both manifests
R=2018-08-17T12:56:34.9830000+02:00 L=2018-08-17T12:56:34.9830000+02:00
TB_Sync - CompareUsingLocal Done Remote Compare
E5855651-DBD1-4532-9FAE-B4BD559CBFEE Remote Compare
44D8DA9F-B918-45ED-8A44-6BDF06F84B55 Debug - written local manifest
Debug - Making remote manifest
at /media/shared/Notes/manifest.xml ERROR - cannot write a new local
manifest file. FCreateError Failed to
open /media/shared/Notes/manifest.xml TApplication.HandleException
Access violation Stack trace:
  $0806315F
  $0822B313
  $0822A558
  $0807DE30
  $0807DA98
  $081B62F7
  $0814CD4B
```
I knew it was not able to write and changed the permissions:
`chmod ug+w -R /media/shared/Notes/`

Clicked <Ok> - no new messages. Instead of letting me to choose between data loss and whatever "Ok" here means, I propose to show a window similar to
> Sync failed. Could not write notes.

Then again: <Synchronise>
> Upload	usage test 40E7242E-3F1D-4800-947C-B255B217A853
Great! Back to user1 checking to import:

```
user1$ tomboy-ng --debug-sync --debug-index
Empty Lists created
Looking for notes in
[/home/user1/.local/share/tomboy-ng/] Checking note
[E5855651-DBD1-4532-9FAE-B4BD559CBFEE.note] Title is [Index]
Checking note
[44D8DA9F-B918-45ED-8A44-6BDF06F84B55.note] Title is [releases]
Checking note
[F9FA8E76-E013-4202-A67C-3C351AE66FF7.note] In
'file:///home/user1/.local/share/tomboy-ng/F9FA8E76-E013-4202-A67C-3C351AE66FF7.note' (line
5 pos 1): Invalid character Finished indexing notes

Backup Dir Checked
TB_Sync - Lists Cleared
TB_Sync - ReadRemoteManifest Done
TB_Sync - ReadLocalManifest Done
This local note contains invalid XML, will NOT sync it.
F9FA8E76-E013-4202-A67C-3C351AE66FF7 In
'file:///home/user1/.local/share/tomboy-ng/F9FA8E76-E013-4202-A67C-3C351AE66FF7.note' (line
5 pos 1): Invalid character Add : File not
found /home/user1/.local/share/tomboy-ng/*.note TB_Sync -
GetListLocalNotes Done TB_Sync - ManifestList Created Done Local sync
E5855651-DBD1-4532-9FAE-B4BD559CBFEE In both manifests
R=2018-08-17T12:58:21.9080000+02:00 L=2018-08-17T12:58:21.9080000+02:00
Local sync 44D8DA9F-B918-45ED-8A44-6BDF06F84B55 In both manifests
R=2018-08-17T12:56:34.9830000+02:00 L=2018-08-17T12:56:34.9830000+02:00
TB_Sync - CompareUsingLocal Done Remote Compare
E5855651-DBD1-4532-9FAE-B4BD559CBFEE Remote Compare
44D8DA9F-B918-45ED-8A44-6BDF06F84B55 TB_Sync - WriteNewManifest Done
```
This is a mess and no sign of 40E7242E-3F1D-4800-947C-B255B217A853,
although the file is there:

```
$ find /media/shared/Notes/
/media/shared/Notes/
/media/shared/Notes/0
/media/shared/Notes/0/2
/media/shared/Notes/0/2/manifest.xml
/media/shared/Notes/0/2/40E7242E-3F1D-4800-947C-B255B217A853.note                                                  
/media/shared/Notes/0/0
/media/shared/Notes/0/0/E5855651-DBD1-4532-9FAE-B4BD559CBFEE.note                                                  
/media/shared/Notes/0/0/44D8DA9F-B918-45ED-8A44-6BDF06F84B55.note                                                  
/media/shared/Notes/0/1
/media/shared/Notes/0/1/E5855651-DBD1-4532-9FAE-B4BD559CBFEE.note                                                  
/media/shared/Notes/0/1/manifest.xml
/media/shared/Notes/0/1/44D8DA9F-B918-45ED-8A44-6BDF06F84B55.note                                                  
/media/shared/Notes/manifest.xml
```
I leave it here.

*available to test alpha .deb*

**Comment by davidbannon** [comment] 2018-08-17 13:33
ok, lots of issues here. I'll try to deal in order.

1. Splash screen not being updated on sync ?  Maybe, but you are expected to have it closed by now ...

2. No, no auto sync. I'm often away from my sync repo, I don't want it. If someone else does, pascal's easy to code ....

3. _Error File Not Found F9FA8E76-E013-4202-A67C-3C351AE66FF7_  is usually caused by an file with invalid xml. Try starting with just --debug-index to find it. You may be able to open it in singlenote mode to fix.....

4. absolutely no requirement to sync after creating a new note.

5.  yep, you get me here. I did not expect some one to point sync at a fs they cannot write to. Best i make a check before starting.

6. I cannot imagine what states the sync is in after 5. above. I have to stick to the Tomboy sync model, and  while there may be better models, tomboy-ng is all about copying Tomboy.

I suggest, if your notes are still in your local repo that you -
a) empty the sync repo inc all the dir under '0'.
b) remove the file (eg) .config/tomboy-ng/manifest.xml in both client systems.
c) start again with write permission to all files.

The file sync is not capable of resolving user permission issues during a sync. You could set stickybits to force all incoming files to have appropriate permissions, not sure, would need to sleep on it.

The tomboy sync model is based on each and every client being able to -
1. update theserver manifest file.
2. create new revision directories
3. write note files into those dir
4. remove a file including ones it did not put there.

goodluck         !

davo

**Comment by davidbannon** [comment] 2018-08-17 23:45
Honestly, I think the real issue here is use of ssh rather than a proper file sharing system. I strongly recommend you use NFS or, perhaps smb if you want to include a windows box in the share. I am not sure if Mac's support NFS so, again, smb might be better.

With either, file permission/ownership is taken care of and tomboy-ng is presented with a clean and working file system.

I can check, before every sync, that we have write permission to server manifest.xml but if I was to drill down below the '0' directory checking every file/subdir, it would greatly delay sync. If its been used for a while, that dir tree gets quite big. Don't blame me, thats how  MOOT designed it.

(MOOT = Masters Of Old Tomboy) - keepers of much wisdom. 

Davo

**Comment by traumschule** [comment] 2018-08-18 01:25
> Honestly, I think the real issue here is use of ssh rather than a
> proper file sharing system.

I don't see how ssh can be an issue. I just used it to execute
tomboy-ng on the same screen as another user via X forwarding (-X).

> I strongly recommend you use NFS

Ok, will try this later.

> perhaps smb if you want to include a windows box in the share.

No plans on windows here :)

Thanks, great work, David!

**Comment by davidbannon** [comment] 2018-08-18 11:59
I am pretty sure your problem was that both users were writing to same directory. Depending on your umask, whoever wrote to manifest.xml first 'owns' it. The other user, using a different PID, is not permitted to write to it when they try to update the file. Some thing applies to other files and dir under there. 

I use an smb share provide by my modem/router and its pretty transparent. You could also use google drive or dropbox (for eg) but I don't want some snoop looking at my notes....

Davo

**Comment by davidbannon** [comment] 2018-08-18 12:04
Anyway, I do now have some checks testing file system access before we firstly setup sync and, secondly, before each sync runs.  However, such checks are not fool proof, they do trust the OS to know the correct answer. My initial tests revealed, for example, that shares mounted in VirtualBox do not know anything about the underlying permissions....

Thats probably best that can be done on this issue. So, might close, feel free to reopen if you like....

**Closed by davidbannon** 2018-08-18 12:04 UTC
