### ISSUE TITLE
Feature: appindicator

### ISSUE THREAD

**Issue by aguador** [tomboy-notes/tomboy-ng#89] opened 2019-03-18 19:26 UTC
Enlightenment no longer supports Xembed notifications (nor does Plasma, but there are likely fewer users there), which means that there is no indicator in Enlightenment's systray which is appindicator compatible. (For an example of appindicator see the Pidgin indicator: https://github.com/philipl/pidgin-indicator.)

A short-term patch would be to do what tomboy does, which is to have the exec command in .desktop default to "search" on startup (something I have hated, but which at least allows access").

**Comment by davidbannon** [comment] 2019-03-18 23:34
Thanks Roy, have seen the email, will work from here to keep relevent data in one place.
I do know this is a major problem. One that annoy me intensely. Background is that Gnome developers decided the (GTK2 inspired) System Tray model was being abused, too much happening in there and (arbitrarily) decided to abandon it completely. I'm using the FPC/Lazarus to build tomboy-ng, it has a 'library' of onscreen widgets uses either the old SystemTray model or Ubuntu's one from its its ill fated Unity experiment, fortunately they still include that in their Gnome3 distros.

So, this problem  exists in RedHat derived distros, they follow the Gnome hard line still.

While there is talk about developing Lazarus GTK4 binding, its a very, very long way off. I have spent some time poking around in the code (and got the Unity version working) the GTK3 AppIndicator is a mystery to me. 

So, my 'solution' was the small '**splash screen'** that comes up, top left. It provides the same menu options as the Systray and also alerts you to any errors. I personally hate it, sounds like you are not keen either !

It would be quite easy to have the **SearchForm** come up on startup but it does not have the menus, they could be added I guess. Do you imagine a SearchForm that opens when tomboy-ng is opened and closing it, shuts tomboy-ng down ?

-------------
**RPMs ?**   Another user alerted me to Alien, I now generate (binary) RPMs directly from the Debs. But I do also have now, in development, a pure command line way of building tomboy-ng on a clean system. You need the Free Pascal Compiler installed already (easy, its in all repos) and then my scripts downloads Lazarus source, compiles the necessary parts, downloads KControls, builds that then, if all is well, builds tomboy-ng from there. Might turn it into a makefile, but easier to work with as a script. It could be basis of a **source RPM**. See buildit.bash in the tomboy-ng source at git.

Davo

**Comment by aguador** [comment] 2019-03-19 20:39
Colour me red! Now that I have taken more time with the final version I see that there actually is a functioning desktop notification working on my system. I am not sure why, but I had tested with while running Vivaldi Browers, installed from outside the distro respository, which also shows the a white triangle with exclamation point. See attached with ng icon. The triagle is the icon that appears in the systray and gives access to search, most recently used notes, and settings.

I do not know about the icon. I think it may have something to do with not being installed from Mageia respositories, but I will leave this open so you can decide whether you want to address the issue at some point.
![tomboy-ng-Enlightenment-systray](https://user-images.githubusercontent.com/8114758/54640143-5c403000-4a8f-11e9-8620-33932b3a5c3c.jpg)

**Comment by davidbannon** [comment] 2019-03-19 22:08
OK, some questions ?
Which desktop are you using ?  I believe Mageia uses both KDE and Gnome (plus others).   I'd expect -ng to work OK on KDE as long as you resolved the GTK dependencies. But I have not tried it myself. 

I am not sure from your description what the white triangle actually is. Is it coming from tomboy-ng and responds with an -ng menu ?  What happens if you click the green icon ? Same menu ?  If you stop -ng, do both icons go away ?

Interesting business ....

Davo

**Comment by aguador** [comment] 2019-03-20 10:35
This is Enlightenment. The Tomboy-ng green icon should really only show for a program with a window open. As there is no open window, it will do nothing. (The same thing happens with Pidgin running in background.) That is a problem with E.

The triangle acts like a proper -ng systray icon giving full access to search, settings, etc. I do not know why it does not show the -ng icon. The only other experience I have with the same icon showing is when I run Vivaldi, except in that case it does nothing. The only thing that Vivaldi and -ng have in common is that they have been installed from outside the Mageia repositories and reside in opt. My suspicion is that E looks for the icons in other places and the triangle is a default "unknown".

**Comment by davidbannon** [comment] 2019-03-20 11:44
Hmm, I wonder if what they have in common is using the deprecated SystemTray model ?
I believe that the icon for the SysTray is built into the binary, unlike the ones used, eg, in menus and docks, its there and unchangeable. So, if the thing shows an icon, it must the the right one. But its not !
Sigh ....
I'm poking around in  code right now, maybe I'll find something that I can do some diagnostics with. I'm trying to find a dependable way to telling if the user can see the icon, not doing very well so far .....

**Comment by davidbannon** [comment] 2019-03-26 10:10
Hmm, I have just run up a VM of Mageia (using Plasma) and -ng seems quite happy (but requires a right click on the Icon rather than a left click ?).   I was not offered a way to setup Enlightenment ...

I would like to run tomboy-ng under strace to workout just what icons it does look for.  Do you reckon you could either outline whats necessary to install Enlightenment or alternativly, install strace yourself, use it to run tomboy-ng and send me the resulting dump ?

Davo

**Comment by aguador** [comment] 2019-03-26 13:51
As a less used DE, you have to select "other" DEs when installing. I normally use the net install which takes you through the same process as the iso.

I'm attaching output from strace. From what I see in searching for tomboy-ng on my Mageia 6 machine, it has installed icons in /usr/share/icons/highcolor, yet strace does not show ng ever looking there. Then again, I am probably missing something.
As a footnote, other programs with appindicators do show their icons properly, e.g., vlc, the pidgin appindicator plugin, and Mageia network and update notifiers.
[ng_strace_out.txt](https://github.com/tomboy-notes/tomboy-ng/files/3008377/ng_strace_out.txt)

**Comment by aguador** [comment] 2019-03-26 13:55
BTW I misspoke a couple of note ago. The part of the panel with the icons indicates all running programs in whatever workspace, including those running in background.

**Comment by davidbannon** [comment] 2019-03-27 00:20
Ah, that may explain what we are seeing. The white triangle is not the Tray Icon, thats internal. So, I think your issue is that under Enlightenment, you don't get to see the Tray Icon at all. 
Yet, from strace, I see you do have libappindicator3 installed and loaded OK. And then writes its image to tmp. How about starting -ng up and seeing if there are some -ng like images in /tmp/appindicators/*  ? Should be small bright green tomboy like image ....
I suspect thats an indication that your system can, or cannot, display appindicators of this type.

**Comment by aguador** [comment] 2019-03-27 16:20
OK, the ng icon does appear in /tmp/appindicators. However it is the only program that uses that location. Two packages that display icons properly in the systray are Mageia's net_applet (showing connection state) and mgaapplet (indicating updates). These were both adapted for Plasma and recently updated by simply including E with Plasma -- and nothing more. I have also activated the Pidgin appindicator and it functions properly in the systray as well. So it is possible to have appindicators working for both Plasma and Enlightenment.
Attaching net_applet so you can take a look at the code. Just search for Enlightenement and you will find (lines 233-234):

if ($ENV{DESKTOP_SESSION} =~ /plasma$|enlightenment/i) {
    $is_plasma = 1;

Literally the only change to that applet was adding "|enlightenment" after plasma in order to activate it for E. The following lines deal with the icon and may help. (I added "txt" as the drag and drop will not function without a file type extension.)
[net_applet.txt](https://github.com/tomboy-notes/tomboy-ng/files/3014244/net_applet.txt)

**Comment by davidbannon** [comment] 2019-03-28 10:40
Yeah, that source you sent is in perl, it will be depending on whatever is in (guess) line 19, "use mygtk3". Tomboy-ng is written in Pascal, and hits the gtk2 interface.  Gtk2 and 3  work together fine except that the Gnome Developers have developed an aversion of one particular gtk2 widget, the System Tray !

Pidgen is a better metaphor, from memory its written in C.

Tell me, the ones you mention, do you click them and see an immediate menu relevant to the application or do you get a generic window sort of menu that might let you then click something to get that application menu ?

While I can nag the Lazarus developers to deliver a GTK3 system tray, truth is we don't know what interface to aim at. Gnome want us to use AppIndicators that, IMHO, don't work interactively enough, lots of people are making Gnome plugins that do, sort of solve the problem (because people need and want this functionality). But that helps only Gnome users. The Gnome Shell Plugin approach won't help with Enlightenment ! Sorry, I don't understand how E relates to KDE, 

In your case, we look for and find libappindicator3, thats about all thats left of Ubuntu's flirt with Unity and its enough to make things work fine on most platforms where its available. But not for Enlighenment. Sigh ...

Davo

**Comment by aguador** [comment] 2019-03-28 18:41
The two Mageia applets give relevant menus -- **as does -ng**. So the systray itself is working. _It is just the icon that is not found._

(The notifier/appindicator failed once at the beginning [leading to the report of this issue] and at least once after that I think was because I closed the "Main form" window too quickly and -ng shut down before loading the appindicator. (I have it set to load at startup.) However, it has been working OK for the last week and a half with at least one startup on that laptop each day.

As I was writing this activated the Pidgin indicator plugin on my other machine . . . and its icon is not found either! Like -ng it is fully functional, but just a triangle with ! in the center. Although the Pidgin indicator has not indicated there is a unresolved dependency, libappindicator-0.1 is listed as a dependency. That is not even available in either the Mageia 6 or 7 respositories. My machines have lib64applidicator2_1 and lib64appindicator3_1. Then again, if the -ng icon showed under Plasma, this should not be an issue.

**Comment by davidbannon** [comment] 2019-03-30 08:04
> It is just the icon that is not found.
Oh, I did not get that. I wonder what it means ?   Perhaps Enlightenment wants the image in a particular format ?  Or size maybe ?  From memory, long time ago, it was a png, no transparancy etc, 24x24 pixels, not a lot of colours ...   
I really would not what to change first .....

tomboy-ng tries to load libappindicator3 first, failing that uses libappindicator, (I have never come across ~2 before!).   

Now, you mention lib64appindicator3_1, just to indulge me, could you make a symlink to libappindicator3.so.1  (in the same directory).

I'll fire up my Plasma install and compare logs ....

**Comment by aguador** [comment] 2019-04-02 14:07
Not quite sure what you mean as I gave you package names, and lib64appindicator3_1 simply installs two files: 
     /usr/lib64/libappindicator3.so.1
     /usr/lib64/libappindicator3.so.1.0.0

**Comment by aguador** [comment] 2019-04-02 14:49
By the way, if you have vlc installed, maybe you could check how it handles the appindicator. It works properly, with systray icon, and I believe Clementine did when I had it installed on one of my machines.

**Comment by davidbannon** [comment] 2019-04-06 03:42
(sorry, been out of range for a few days)
/usr/lib64/libappindicator3.so.1
Ah, OK, if thats there, it will be used. Its a symlink to /usr/lib64/libappindicator3.so.1.0.0 i expect.

I am afraid I am starting to assume the issue is an Enlightenment one. Libappindicator3 is present, apparently being loaded and is the (FPC/Lazarus) preferred way to do things that look like (but may not officially be) System Tray. The fact that it works fine under Plasma with otherwise the same system really says to me Enlightenment. 

So, maybe you need to log an issue with enlighenment project ?

I have been coding  up a way to provide a main menu on the search window as you requested but it has turned out a bit more complicated that I thought as I cannot 'reuse' the System Tray menu. Making a second menu is a bit error prone so am refactoring that whole area. That means a bit longer and a lot of testing needed !

David

**Comment by davidbannon** [comment] 2019-04-10 04:59
Just been playing ....
https://wiki.mageia.org/en/Mageia_6_Release_Notes#Enlightenment says -

> Third, E21's system tray, based on SNI notification, seems not to be fully functional and, since E20, has not supported Xembed notifications. If you need Xembed notifications, you can try installing the wmsystemtray. 

I have built a QT5 based version of tomboy-ng, just to see if it solves the Fedora issue (no!) and wondered if it might help you. But I cannot add enlightenment to my test install, the wiki says the package manager includes an enlightenment meta package but not in my case. Strange ....
Its a messy solution anyway, requiring the selective install of libQt5Pas .....

**Comment by aguador** [comment] 2019-04-10 14:42
OK, reassembled the laptop (still without fan) and tested Pidgin's appindicator which indeed has the same problem. Will check with the E list to find out what is happening.

**Comment by davidbannon** [comment] 2019-06-14 03:03
Have found some very interesting facts.  On, for example, Fedora, installing TopIcons-plus AND a library called  libappindicator-gtk3 gets things working as they should, no more having to disable wayland !
Similarily, on openSUSE but library is called (a more familiar) libappindicator3-1.  Not that both TopIcons-plus and the library are required.
I have not yet started docing this ....

**Comment by davidbannon** [comment] 2019-10-15 11:02
as of 0.24, I now have a much greater understanding of what we can (and cannot) do with System TrayIcon.  There is now a way to force using the alternative and I have pushed a number of changes upstream so that LCL makes better guesses between the older System Tray Icon and LibAppIndictor3
It sort of works on Enlightenment but does not show the correct icon.

**Closed by davidbannon** 2019-10-15 11:02 UTC
