### ISSUE TITLE
cannot load RPM

### ISSUE THREAD

**Issue by tuxedotje** [tomboy-notes/tomboy-ng#102] opened 2019-09-20 14:17 UTC
Last metadata expiration check: 0:00:31 ago on Fri 20 Sep 2019 04:12:10 PM CEST.
Can not load RPM file: tomboy-ng-0.23-2.x86_64.rpm.
Could not open: tomboy-ng-0.23-2.x86_64.rpm
0n Fedora 31 beta.

**Comment by davidbannon** [comment] 2019-09-20 23:36
Thanks for that report tuxedotje, afraid I will need more information please. I guess you have successfully downloaded the rpm file ?  And are now using an rpm command to install it ?  I don't know if those error messages mean that the rpm command is finding something wrong with the tomboy-ng package or if it cannot find the package.

Could you please show me the commands you are using ?  

Maybe type - 
ls -la
and then the command you are using. And then copy that part of the screen and paste it here.

(You know, generally, its far better to post a bug report that too long rather than one thats too short !)
Davo

**Comment by davidbannon** [comment] 2019-10-03 10:46
tuxedotje, are you there ?

As a matter of interest, I have just noted that both yum and dnf are generating messages to the effect -
```
" Problem : conflicting requests
- package tomboy-ng-0.23f-2.amd64 does not have a compatible architecture"

```
I don't know why, the binary in there is definitly of the right are architecture. And the rpm command works fine. A mystery ..

`rpm --install ./tomboy-ng <....etc>`

If you have also seen this message, please let me know ....
Davo

**Comment by tuxedotje** [comment] 2019-10-03 13:35
On Fedora 31 goto https://github.com/tomboy-notes/tomboy-ng/releases/tag/V0.23  (tomboy-ng install)
click on   tomboy-ng-0.23-2.i386.rpm
"Software" will install . no comments. (Software is the name of an  installer in Fedora, confusing name)
The amd version cannot installed, problems there. (cannot read the problems)

**Comment by davidbannon** [comment] 2019-10-03 22:35
OK, tuxedotje, is your system 32bit or 64bit ?  From what you say, it sounds like it could be 32bit. If you do have a 64bit system, might be worthwhile trying to install a downloaded file from the commandline as root. Using the rpm command - (from memory).
`rpm --install ./tomboy-ng.....`
You need to be quite specific with the command line, give the full file name with the leading ./   else rpm will try and find the package in its repositories. And, this is a catch, I suspect rpm does not resolve dependencies. I think that should not be a problem, tb-ng does not generally have dependencies that are not normally pre-installed. But, well, you know !
 But you can continue using the 32bit if it works OK for you, no problems.
Yeah, "Software" - not much of a name. Thats Gnome's influence, a very strong influence at RedHat. A number of other Distros are doing the same thing. But I guess it means someone, like me who jumps around between distros a lot can always fine what they are looking for, even if its a different app underneath.  In the Ubuntu distros, "Software" does a really bad job of resolving dependancies ! Sigh.

**Comment by tuxedotje** [comment] 2019-10-04 09:03
-------- Forwarded Message --------
Subject: 	Re: [tomboy-notes/tomboy-ng] cannot load RPM (#102)
Date: 	Fri, 04 Oct 2019 11:01:31 +0200
From: 	Jaap <jjb@xs4all.nl>
To: 	Jaap Bosman <jjb@xs4all.nl>



On Fri, 2019-10-04 at 10:56 +0200, jjbmac wrote:
> Hi Dave davidbannon
>
> On my iMac "Core 2 Duo" 2.66 20-Inch (Early 2008) 2.66 GHz Core 2 Duo
> (E8335) (which is 64bit)
>
> in F31 This is not different from the "Software" install.
>
>
> On another PC Intel i3 64 bit (Fedora 30) different story 
[jaap@linux-2 Downloads]$ rpm --install ./tomboy-ng-0.23-2.i386.rpm 
error: Failed dependencies:
libX11.so.6 is needed by tomboy-ng-0.23-2.i386
libatk-1.0.so.0 is needed by tomboy-ng-0.23-2.i386
libcairo.so.2 is needed by tomboy-ng-0.23-2.i386
libgdk-x11-2.0.so.0 is needed by tomboy-ng-0.23-2.i386
libgdk_pixbuf-2.0.so.0 is needed by tomboy-ng-0.23-2.i386
libglib-2.0.so.0 is needed by tomboy-ng-0.23-2.i386
libgmodule-2.0.so.0 is needed by tomboy-ng-0.23-2.i386
libgobject-2.0.so.0 is needed by tomboy-ng-0.23-2.i386
libgthread-2.0.so.0 is needed by tomboy-ng-0.23-2.i386
libgtk-x11-2.0.so.0 is needed by tomboy-ng-0.23-2.i386
libpango-1.0.so.0 is needed by tomboy-ng-0.23-2.i386
libpangocairo-1.0.so.0 is needed by tomboy-ng-0.23-2.i386
[jaap@linux-2 Downloads]$

**Comment by davidbannon** [comment] 2019-10-07 10:46
Sorry tuxedotje, I really don't understand the last message (dated October 4th)!

There seems a block that consists of a message forwarded from someone called Jaap using a 64 bit Mac and then a report from a failed install or some 32bit tomboy-ng and a whole lot of reproduced text written by me. Sorry, just what are you trying to tell me ?

Generally, no matter what app you are installing, if you are using a 32 bit system, you should install the 32 bit package, it typically has i386 in its name. If you are using a 64bit system, it will usually have amd64 in its name. Thats the right package for either Intel or AMD systems by the way. 

Now, going back to the start of your question, you seem to be trying to install "tomboy-ng-0.23-2.x86_64.rpm", thats not what the install rpm is called, its (in v0.23) "tomboy-ng-0.23-2.amd64.rpm". I have used this naming scheme since the very early days of tomboy-ng. If you have downloaded something with the first name, I suggest you be very careful, that sounds quite suspicious to me.

I am currently testing the next release of tomboy-ng and doing so on quite a lot of different systems including Fedora 30 in several different manifestations. In every case, I find I cannot use yum or dnf but rpm --install ./<filename> works fine and does not seem to trigger any dependancy issues. I did on one occasion all it to install to the "Software" app direct from the web page and that did work but I do not recommend that as it does not show you any warnings or error messages, on some 'spins' it worked, on others it errored out, you can tell the difference.  I recommend downloading the file and then -

`sudo rpm --install ./tomboy-ng-0.23-2.amd64.rpm`

from the directory you have downloaded to. While I have discovered a number of bugs, mainly i18n related, I have not ever had a problem with the install. But I am testing against Fedora29 and Fedora30. Please remember 31 is still in beta !

For your sake I tried to Fedora31beta but could not get it to run in VB so decided to wait until its just a bit more mature.
Davo

**Comment by davidbannon** [comment] 2019-12-20 06:44
Not heard back from tuxedotje.
As I am about to release v0.25, would be good to know if he is still experiencing issues.
General advice is to download the rpm file, then use the rpm command, at the command prompt, to install.  I do not recommend use the (gnome) 'Software' application, previous experience says its not good at installing anything other than packages in its own official repository.

**Comment by davidbannon** [comment] 2019-12-26 07:04
Have to assume problem related to tool used to install.
On rpm based systems, please use rpm.

**Closed by davidbannon** 2019-12-26 07:04 UTC
