### ISSUE TITLE
Marked text should become a link when "Link" button is clicked

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#12] opened 2017-11-28 06:16 UTC
# Expected
Marked text becomes a link when the button "Link" is clicked and a new note with that title opens.

# Observation
~Nothing happens.~

~Might be limited to Linux/i386.~
- a new note with that title opens
- the marked word becomes no link
- the note does not appear in the tray menu directly nor in the search list or in the ./Notes directory
- as soon as I start typing, it is saved and appears on disk and in the tray. 

I guess this is confusing. Could we save directly after opening the note?

On first save it shows up in the search list like the first row in the attached image (with overlong timestamp), the next save (eg closing the note) however corrects it.
![tomboy_newnote](https://user-images.githubusercontent.com/31551045/33379637-a89ead32-d510-11e7-9e5e-dd71c862588f.png)

**Comment by davidbannon** [comment] 2017-11-29 00:25
No, not an i386 issue, just a case of bad regression testing.
I believe its now fixed in source.

**Comment by traumschule** [comment] 2017-11-29 00:52
unfortunately not, still there + #14

**Comment by traumschule** [comment] 2017-11-29 02:59
> is the Link button working as expected ?
not with ac9a77d68dabc8b64f7229db7fcb0662ee85211d

**Comment by traumschule** [comment] 2017-11-29 03:49
Adding `OnClick = ButtLinkClick` in editbox.lfm, but still then the new note window is only opened but not added to the register (checked with search).

**Comment by davidbannon** [comment] 2017-11-29 06:49
Reopened.
I suspect this is my bad. ObjectPascal is perhaps not a great model to use under git. Trouble is lfm files change as soon as you move the form, perhaps to see whats behind it. I reckon I have not uploaded the editbox.lfm file after adding an event for the Link button (ignoring Gits prompting).  I'll push my current one now. Please delete your existing lfm file and pull down the new one.

**Comment by traumschule** [comment] 2017-11-29 14:28
That's what I thought. Do you check for changed files with `git status` before committing? Git is awesome, it tells me about remote changes on `git pull` and suggests `git stash` to temporarily move them aside. I can then pull and `git stash pop` to reapply them resulting in merge conflicts which I resolve with `git mergetool -t meld` - no need to delete for me. After I added files when conflicts are resolved, i it stash drop` to delete the stashed version.

New behavior:
- I open a note, select a word, click link and a new note with that title opens. GREAT!
- the marked word however becomes no link
- the note does not appear in the tray menu directly nor in the search list or in the ./Notes directory
- but as soon as I start typing, it is saved and appears on disk and in the tray. I guess this is confusing. Could we save directly after opening the note?
- on first save it shows up in the search list like the first row in the attached image (with overlong timestamp), the next save (eg closing the note) however corrects it.
![tomboy_newnote](https://user-images.githubusercontent.com/31551045/33379637-a89ead32-d510-11e7-9e5e-dd71c862588f.png)

Note that `RichMemo1LinkAction` in `editbox-ref.pas` is unused:
```
procedure TEditBoxForm.RichMemo1LinkAction(Sender: TObject;
    ALinkAction: TLinkAction; const info: TLinkMouseInfo; LinkStart,
    LinkLen: Integer);
	// Note as of August 2017, this funtion is incomplete in Win10
	// Cannot rely on LinkStart or LinkLen so workaround.
	// http://forum.lazarus.freepascal.org/index.php/topic,37909.0.html
var
     Index, Len : longint;
begin
    Index := RichMemo1.SelStart;
    Len := 0;
    while RichMemo1.IsLink(Index) do dec(Index);
    inc(Index);
    While RichMemo1.isLink(Index + Len) do inc(Len);

    // Ahh, but what if user has changed the note's title ??
    if RichMemo1.GetText(LinkStart, LinkLen) <> NoteTitle then
    	SearchForm.OpenNote(RichMemo1.GetText(Index, Len));
    // SearchForm.OpenNote(RichMemo1.GetText(LinkStart, LinkLen));
end;      
```

**Comment by davidbannon** [comment] 2017-11-29 21:56
Easy one first, editbox-ref.pas is not used and should not have been submitted to git. I'll work out to delete it ...
I personally don't use the Link button (or internal links) so am not in tune with how it works. I actually hate the way it links to things that often have no relevance !  So, when making a new page, I (with my mindset) gave the user an opportunity to no make a new note unless they wrote to it. Sounds like you don't like that model ? I should not assume ...
I can easily do a save on opening, its easy to detect, I have a title but no file name.
And I have not truncated the long datetime string, don't know how I missed that. 

Lets leave this ticket open to fix -

- **Immediately save a note begot by the Link button (even though I don't like it :-) )
- Truncate the date time string for above note.**

And no, I have not been always saving lfm files when the only change has happened because of a moved form. The updated lfm entry in git would be labeled with that real commit which would have nothing to do with the lfm file. I'd better review that policy.

**Comment by traumschule** [comment] 2017-11-29 22:41
i agree it's rather low priority, if in doubt we should mimicked Tomboy NG's behavior.

**Comment by davidbannon** [comment] 2017-11-30 00:34
Yeah, thanks, have removed that and another -ref file. Should not have been there in the first place.
I cannot add lfm to gitignore because sometimes changes to the lfm file are important. Like it the case you found where the link button did not have its event registered. I think its a case of being more careful.

**Comment by davidbannon** [comment] 2017-11-30 01:37
OK, updates pushed.
change dates in search box for new notes shown cleanly.
A new note created by clicking Link button in another note is saved immediately.
The text selected when that Link button was clicked becomes a link.

I think this issue is closed ??

**Comment by traumschule** [comment] 2017-11-30 01:52
Thanks! Will check right now ..

**Closed** 2017-11-30 01:57 UTC
