### ISSUE TITLE
Error when  setting file sync repo

### ISSUE THREAD

**Issue by amuehlhause** [tomboy-notes/tomboy-ng#138] opened 2020-01-30 14:12 UTC
With tomboy-ng64_0.26.dmg on macOS Catalina 10.15.2 (19C57) I get following error when clicking on menu->settings->sync-> Set File Sync Repo -> select folder (e.g. "/Users/username/Documents/untitled folder") -> "Create a new repo?" -> yes:

```
In 'file:///Users/username/Library/Application%20Support/Tomboy-ng/Notes/4951BF38-3B06-EC98-F36E-8033C8D2205F.note' (line 7 pos 3): Unmatching element end tag (expected "</size:huge>").

Press OK to ignore and risk data corruption.
Press Abort to kill the program.
```
When I press "Abort" it kills tomboy. When I click "OK" the dialog closes and I see the sync settings window. Obviously nothing happens. When I click "Menu->Synchronise"  the following message is shown up:

`Please config sync system first`

**Comment by davidbannon** [comment] 2020-01-31 00:10
The actual error reported relates to a bad bit of XML in one of your notes.  I assume you are not being told about it when you start tomboy-ng up ?    If not, I am a bit surprised.

Could you please have a look in this note with the Finder -
` 
/Users/username/Library/Application%20Support/Tomboy-ng/Notes/4951BF38-3B06-EC98-F36E-8033C8D2205F.note
`

and see if it contains anything you would mind posting to me ?  I am a bit unhappy that its got as far as trying to sync without being flagged as bad XML.  

Please save it if you can, it you don't consider its content important, you could delete it and restart tomboy-ng and you will possibly find everything works OK.

**Comment by amuehlhause** [comment] 2020-02-01 23:22
It was a nearly fresh install of tomboy-ng. So I don't mind. I don't get any warning at startup (the note is not shown up anymore in the UI). Here is the content of the given file:

`<?xml version="1.0" encoding="utf-8"?>
<note version="0.3" xmlns:link="http://beatniksoftware.com/tomboy/link" xmlns:size="http://beatniksoftware.com/tomboy/size" xmlns="http://beatniksoftware.com/tomboy">
  <title>test</title>
  <text xml:space="preserve"><note-content version="0.1"><underline>test<size:huge>


</underline><monospace><underline><highlight><bold>asdasda</bold></highlight></underline></monospace></size:huge>

asdasd
</note-content></text>
  <last-change-date>2020-01-30 14:24:26</last-change-date>
  <last-metadata-change-date>2020-01-30 14:24:26</last-metadata-change-date>
  <create-date>2020-01-30 14:24:26</create-date>
  <cursor-position>1</cursor-position>
  <selection-bound-position>1</selection-bound-position>
  <width>617</width>
  <height>497</height>
  <x>551</x>
  <y>327</y>
  <open-on-startup>False</open-on-startup>
</note>`

**Comment by davidbannon** [comment] 2020-02-02 01:36
Yep, that note has a crossed over tag, huge is turned on just after the title and before the titles underline is turned off.   
OK amuehlhause, thats all pretty strange. Firstly how you ended up with a note like that, we have to assume that it was made by tomboy-ng and thats my bad.
Secondly, why that bad note was not and is not being flagged as such. I put it in my note repository, restarted tomboy-ng and it immediately opened the small splash screen with a warning about a bad note and how to fix it.  I will have to repeat that test on my Mac, my test so far was just linux.
I will have to try to recreate that bad note too.
Will get back to you ....
Davo

**Comment by davidbannon** [comment] 2020-02-02 07:31
OK, you have found and exposed a bug that has been there since day one ! With right conditions, it is possible to write out bad xml. The interesting thing about this bad xml is than when loaded into tomboy-ng (and it loads OK) it then gets written out with the same problem. I have built in a lot of sanity checks but missed that particular possibility.

My guess is what happened is you were trying out a range of font parameters and put them all on the first bit of text, when the file was saved, because of my bug, a bad note was written out. You then tried to sync and the sync system was pointed to the bad note, after all, it had just been saved so must be OK.  Sigh.
Fill be fixed in next release.
Thanks heaps for your report  amuehlhause, it was quite a nasty bug, surprising it had not been picked up earlier.
Davo

**Comment by amuehlhause** [comment] 2020-02-02 18:38
Your assumptions seem to be valid since I tested a bit around with my first note ;). So yes its realistic that I applied a lot of font options to the first word. Please let me know if you need any help in order to reproduce the selected font options (maybe order etc.) ... or did you already found it?

For the rest: no worries. Thank you.

**Comment by davidbannon** [comment] 2020-02-02 23:08
Thanks Aldo. No need to reproduce the exact scenario, I just need to be (absolutely ?) sure its not written out using bad xml. Any combination you can dream up should be legal, its turning that combination into legal Tomboy xml thats the issue !
What I have here now has passed all the tests I can dream up, thats not absolute but must be pretty close. I hope ....
Davo

**Comment by davidbannon** [comment] 2020-03-15 08:19
OK, I am pretty sure v0.27 has fixed this.
Davo

**Closed by davidbannon** 2020-03-15 08:19 UTC
