### ISSUE TITLE
Enhancement: Notes should open focused on the first line, not the last

### ISSUE THREAD

**Issue by benjbrandall** [tomboy-notes/tomboy-ng#52] opened 2018-06-27 09:57 UTC
Using single note view on Notes.txt in the source opens Notes.txt having already scrolled right to the bottom of the note.

Replicate:

Clone the latest source, build, and then do:

`./tomboy-ng -o Notes.txt`

![single note scrolled to the bottom](https://user-images.githubusercontent.com/15836153/41967169-ad05eb12-7a09-11e8-95cf-963eb00120bf.png)

**Comment by davidbannon** [comment] 2018-06-27 10:31
Hi Ben !
Yeah, setting the cursor is an issue with normal tomboy notes too. Tomboy it self saves last used position and restores it. Thats on the ToDo list for tomboy-ng.  But in the case of an import, that won't work so, yeah, either beginning or end ?

**Comment by benjbrandall** [comment] 2018-06-27 10:39
Ok cool! I couldn't figure out where the loading cursor function was setting the load state, is there something as simple as setting it to focus on the first line? If so, would you mind showing where in the code?

**Comment by davidbannon** [comment] 2018-06-27 11:10
Right now, we are not setting the cursor position at all. It just happens to end up at end of file at load.
It should be done, I believe, using one of two methods -
1. something like this - KMemo1.ExecuteCommand(ecCopy); assuming there is a command to move the cursor to to a specific position (instead of ecCopy which is obviously for copying).
2. Setting the selection begin and end to position 1 or is that 0 ?   KMemo.SelStart := 

Davo

**Comment by benjbrandall** [comment] 2018-06-27 15:24
Solution: https://github.com/tomboy-notes/tomboy-ng/pull/54

**Comment by davidbannon** [comment] 2018-06-28 09:22
OK, fixed with patch from Ben, all good.

**Closed by davidbannon** 2018-06-28 09:22 UTC

**Comment by aguador** [comment] 2020-04-01 07:07
A regression? I am seeing this regularly in 0.27 Gtk, annoying because I have a series of journal-style notes in reverse chronological order.

**Comment by davidbannon** [comment] 2020-04-02 04:23
Hmm, Ben's original report related to Single Note Mode, is that where you see this problem ?

The cursor should end up on the first non-title line.  Mine does, in both Single Note Mode and normal mode.  What happens is that content is loaded into kmemo and that leaves the cursor at the end.  After loading, I move it to top of document.

I actual fact, the Tomboy format has a field that stores the last position of the cursor and it should be restored to your last typed position on load. One day ...

When you say "seeing this regularly", do you mean always, sometimes, occasionally ?

Davo

**Comment by aguador** [comment] 2020-04-02 07:20
Bah, did not read the original post carefully, just wanted to avoid duplicating a problem. I see this in regular mode always. This happened in a prior release in regular mode as well, but I do not recall which. It was a while back. I just double checked with 0.27 and a couple of notes in my Mageia 7 machine.
