### ISSUE TITLE
&amp; in notes sometimes gets changed to &&amp;

### ISSUE THREAD

**Issue by erik-brangs** [tomboy-notes/tomboy-ng#63] opened 2018-07-12 19:12 UTC
Sometimes, my notes with & in them are being corrupted. The notes are correct at first and some time later they might get corrupted. The corruption becomes apparent because they can't be synced. When looking at the sources of the notes, it seems that "&amp;" is getting changed to "&&amp;" for some reason. I haven't been able to locate the cause or trigger this at will.

**Comment by davidbannon** [comment] 2018-07-13 01:23
There are some characters that should not be allowed to remain intact in the XML file. Such as '<' and '>'. I am pretty sure & was not on the list but might be wrong, or maybe it should be on the list ?
I'll have a good look at the source if I get a chance latter today.
Davo

**Comment by davidbannon** [comment] 2018-07-13 03:35
No, I was wrong, we do mess with &, obviously, it how we id special char. Sigh...
Seems to be working OK for me, tried swapping a note back to Tomboy. Multiple & also get correctly converted.
Now, Erik, I know you are on Windows and I am testing on Linux, don't have a windows machine available to me at present, so, is there a windows only issue ?  Might be work trying specifically the & at the end of a line, thats one area where the Unix/Windows differences exist. Or beginning ...
Davo

**Comment by erik-brangs** [comment] 2018-07-13 06:13
The occurrences were always in the middle of the line.

As I said, I wasn't able to make it fail. But the problem seems to occur sometimes after trying to sync an edited note.

**Comment by davidbannon** [comment] 2018-07-13 10:50
Hmm, be great if you could post a copy of an offending note. Perhaps post to me directly (ie not through git or the mailing list) if its something you don't mind me seeing.

When syncing, we don't check too much of the xml, no where near as much as when a note is first indexed (ie at startup or following a refresh from from the search window). So, it would be interesting to see if you can press the refresh button and see an error flagged.

A bad note will remain in your repo until you over write it using sync or manually delete it. If it cannot be indexed, it won't appear in the search lists. Loading a note is deliberately done differently from indexing, in a way that is much more tolerant of bad xml so, if you know its name, you could (or might be able to) open it in tomboy-ng in single note mode, make a trivial change causing it to be saved. And that should fix any problem.

If it won't open in single note mode, then to recover it will take some manual editing I'm afraid. Carefully.

david

**Comment by davidbannon** [comment] 2018-07-24 09:12
no further thoughts on how to reproduce this problem Erik ?

**Comment by erik-brangs** [comment] 2018-07-24 21:01
Unfortunately not. I was going to look on Windows because I thought I might have had a failing note. However, my manifest.xml on my synchronization folder got corrupted somehow (first 209 lines are text then it switches to non-text characters), so I can't try synchronization right now. Is there a way to rebuild the manifest.xml?

**Comment by davidbannon** [comment] 2018-07-24 22:57
Hmm, in theory, yes, I reckon it should be possible. But there are, to the best of my knowledge, no tools around to do so.
Do you have a valid and complete set of notes elsewhere ?  Or do you have some notes on (eg) windows and some your linux box ?

**Comment by erik-brangs** [comment] 2018-07-25 06:44
Well, I tried to recover by making a new sync from my Linux machine but that seems to have been incomplete for some reason (probably bad unmounting). Syncing with that repo lead to doubled notes on Windows.

So I tried to make a new sync repo from the state on Windows. This seemed to work at first but a few syncs later the local Windows manifest.xml has disappeared. So I suppose the best set that I have is the note set with the corrupt manifest.xml because the other notes there are probably ok.

How could I reconstruct the manifest.xml from the other data?

**Comment by davidbannon** [comment] 2018-07-25 09:49
OK, does not sound good. I assume you are getting double notes (on windows) via Tomboy rather than tomboy-ng ? I have never quite understood how Tomboy ends up with that double note process and am pretty sure tomboy-ng won't. (but you might tell me otherwise....)

Making a new manifest won't be easy, I think extracting the newest version of each note (in the sync repo) to make a new note directory and then allowing Tomboy/tomboy-ng to make a new sync repo might be a better approach. But I suspect that might also recover notes you have deleted.

 I'll need look over my notes about how the sync repo is constructed.

David

**Comment by erik-brangs** [comment] 2018-07-25 16:35
The problem with the double notes happened with tomboy-ng; I haven't used Tomboy in a while.

I'll try to see if I find a suitable state to recover from one of the systems.

**Comment by erik-brangs** [comment] 2018-07-25 17:03
How can I get tomboy-ng on Windows to create a new manifest.xml? As I said before, the old one simply disappeared.

I tried switching the note directory (but not the settings) and adding a new note and then syncing but sync fails because manifest.xml is missing.

**Comment by davidbannon** [comment] 2018-07-25 23:41
Yeah, I think it would.
You need to point sync to a clean directory AND remove the local manifest file in the config directory. tomboy-ng will then see it as a new sync and will create necessary files and dir structure.
davo

**Comment by davidbannon** [comment] 2018-07-25 23:43
tomboy-ng makes double notes ?? Ahhhh !
Can you please check for me if a doubled note has different file names ?  I believe it has to but I don't see the mechanism used to create the new file name. Thats something I really wanted to avoid 'cos it really annoyed me in Tomboy.
I just cannot imagine the process thats taking place.....

**Comment by erik-brangs** [comment] 2018-07-26 06:04
Yes, the file names are different.

**Comment by davidbannon** [comment] 2018-07-28 02:56
Oh, wow, thats very confronting !
I am quite sure the code in TB_Sync does not know how to request a new note name.
Erik, when you say "the file names are different" both are of the GUID format ? That is the 32 hexadecimal characters with a few dashes thrown in ?

**Comment by erik-brangs** [comment] 2018-07-28 07:20
Yes, they both have the GUID format. The contents also seem to be the same (the SHA1 hash of the files is the same).

**Comment by davidbannon** [comment] 2018-07-29 01:09
This is a total mystery to me. I have been through the two units that are active during sync and there is only one call to getGUID and thats used to create a new Sync Repo GUID, not a file name. There is no code there that can duplicate a note.
Unlike Tomboy that has an option to duplicate clash notes, tomboy-ng does not think that way. And it does not have an option to "do the same to all notes" either. 
Erik, is there any chance the duplication happened in the sync repo from another machine that does have Tomboy installed ?
I really don't know how to try and reproduce this problem. But its one I would really like to address.
Davo

**Comment by erik-brangs** [comment] 2018-07-29 06:49
I had Tomboy installed on Windows but I didn't use it. I suppose it would be possible that I got confused and accidently used it. I suppose I'll have to wait and see if this occurs again. I'll do the same for the problem with the ``&`` getting changed.

**Comment by davidbannon** [comment] 2018-07-29 07:29
OK, thanks Erik, I'll leave this ticket open for a a while so we have place to focus.

**Comment by davidbannon** [comment] 2018-08-17 23:49
OK, this is definitely fixed in 0.18.
Was being caused by a unicode character ahead of the a '&' in title.  That, obviously should be quite legal, however my code to deal with the '&' was not unicode compliant. Sigh.

**Closed by davidbannon** 2018-08-17 23:49 UTC

**Comment by erik-brangs** [comment] 2018-08-19 12:38
AFAICT it's really fixed. I haven't seen it since using the new version. Thank you.
