### ISSUE TITLE
CTRL+N not working if the focus is not on Search box.

### ISSUE THREAD

**Issue by turgutgenc1** [tomboy-notes/tomboy-ng#226] opened 2021-02-08 02:04 UTC
In the search window, if the cursor is in the Search area, Ctrl  + N creates a new note without a problem.
If the cursor/focus is somewhere else, Ctrl + N does not create a new note.

Using 0.31h on Windows 10.

**Comment by davidbannon** [comment] 2021-02-08 05:13
Thats because the Ctrl-N does not get delivered by the OS to tomboy-ng so it cannot take any action.  If you want an OS wide Ctrl-N you would need to tell your OS about it and I would need to provide a way to create a new note from the command line, both, IMHO pretty trivial additions.  I think :-)

I would add a command line switch to -ng that makes a new note when you give this command -

`tomboy-ng --new-note`

And you would tell your OS when ever you typed Ctrl-N it should issue the above command.

Davo

**Comment by turgutgenc1** [comment] 2021-02-08 10:48
I believe you've misunderstood the situation.
Tomboy-ng Search window have a "Search" text box which is for typing. When the cursor in that textbox, CTRL+N works like a charm.

When the cursor is not in the textbox, but the Tomboy-ng window still has the active OS focus (focus on list of notes for an example, or Notebooks pane on the left), CTRL+N doesn't work. Focus is not stolen.

I don't suppose the OS would hold back sending the signals to any application when the application has the OS focus.

I hope this clears the air?

**Comment by davidbannon** [comment] 2021-02-08 11:18
Yeah, I do, I can reproduce what you suggest. Thats definitely not as intended. Will be fixed, probably in v0.33
Thanks for reporting that !

Davo

**Comment by davidbannon** [comment] 2021-02-11 08:27
OK, there is a experimental version in the Github Release page, https://github.com/tomboy-notes/tomboy-ng/releases/download/v0.32/tomboy-ng-setup-0.32a.exe

This package addresses two things at once, it writes a few debugln when exiting from Search Form to help debug an issue and fixes the bug reported here.  If it works for you, seems no reason why you should not use it until we push out the next formal release.

Please let me know what you find.

Davo

**Comment by turgutgenc1** [comment] 2021-02-11 13:58
I confırm it works for most. It only doesn't work when the focus is on one of the checkboxes at the top: "Case sensitive" or "Auto Refresh".

This version also seems to have resolved the Right Alt + Q issue on Turkish keyboard.

**Comment by davidbannon** [comment] 2021-02-11 22:23
> It only doesn't work when the focus is on one of the checkboxes at the top: "Case sensitive" or "Auto Refresh".

Ah, I did not make key handlers for the checkboxes because they don't hold focus, maybe on Windows they do ?  That might mean we have same issue with the Speedbuttons (Refresh and Clear Filter). Further research is indicated ....

Thanks ...

Davo

**Comment by davidbannon** [comment] 2021-02-24 06:23
OK, this issue is fixed in version 0.32b, will close.  
Thanks for the report.
Davo

**Closed by davidbannon** 2021-02-24 06:23 UTC
