### ISSUE TITLE
Why not menu bar?

### ISSUE THREAD

**Issue by vassilisw** [tomboy-notes/tomboy-ng#290] opened 2023-02-27 17:36 UTC
Is there any reason behind the lack of the main menu bar?

**Comment by davidbannon** [comment] 2023-02-28 11:13
Not particularly.
The user interface was based, copied more correctly, from the original Tomboy. It has evolved a little, in particular the way the "menu" button appears everywhere to help solve an issue caused by Linux Gnome's war against the System Tray Icon.
Do you particularly need a traditional main menu ?  On the note edit window, the settings or search windows ?
Not something I have thought about but certainly can consider....
Davo

**Comment by vassilisw** [comment] 2023-02-28 19:35
It's not that I personally indeed need the main menu, though classic design gui patterns require a main menu that hosts all the app's functionality.
Of course, there is that other outrageous in my opinion trend towards CSD, but honestly I wouldn't go this way since Gnote app already is one of them.
Additionally, a note-app like this could be considered native to desktops like Mate, unlike Gnote.

**Comment by davidbannon** [comment] 2023-03-05 07:33
Yep, thats one of Lazarus's key strengths, write once and it looks 'local' (nearly) everywhere.
And tomboy-ng is always well tested on Mate, its my preferred Desktop !

Davo

**Comment by davidbannon** [comment] 2023-09-14 11:03
I guess we can close this 'issue"
Davo

**Closed by davidbannon** 2023-09-14 11:03 UTC
