### ISSUE TITLE
Nested Sub-Bullets missing

### ISSUE THREAD

**Issue by xypd** [tomboy-notes/tomboy-ng#84] opened 2018-11-12 17:37 UTC
Hey David,

Will you be adding sub-bullets to tomboy-ng?

I noticed that it was missing and reformatting my notes on my phone (tomboy clone).

I'm running a Mac 10.13.3

Hoping for something like this:
<img width="729" alt="bullets_issues" src="https://user-images.githubusercontent.com/23583395/48364845-7b5d2a00-e677-11e8-807c-fa26a3df6bd1.png">

**Comment by davidbannon** [comment] 2018-11-27 22:51
Ah, I'm home again. Can get to deal with some of these issues !

Thanks XYPD, yep, it does not support nested bullets. No reason why not apart from me not getting around to do it.  Honestly, I am quite unhappy with how bullets work on tomboy-ng anyway and just realised I unconsiously avoid using bullets for that reason !
Long term, its a rewrite of the bullet code, make the inset cnsistent and provide nested bullets. 
But, no promise its going to happen quickly....

We'll leave this ticket open to remind me of the need to do it.

Davo

**Comment by xypd** [comment] 2018-12-03 04:15
Thanks for the update on the look of the bullets. I have no idea how hard it is, but appreciate you considering tackling it. It something I personally use often. But I have adjust my usage for now. Since  it conflict with my mobile version (conflict ... meaning it removes them any sub :( ).

**Comment by davidbannon** [comment] 2018-12-06 05:37
OK. Interesting.  Can you tell me more about your "mobile version" ?  Application ? Platform ? Sync ?

davo

**Comment by xypd** [comment] 2018-12-06 16:39
I use an obscure mobile platform called maemo. It's run debian with a fork on gnome. You can find some info [here about Conboy](http://conboy.garage.maemo.org/)

I sync using owncloud/nextcloud, by choose the same directories on both the desktop and phone. It's been fantastic for getting my notes to the desktop. I might be changing that sync to rsync soon though, since my phone doesn't support newer versions of most stuff now days.

**Comment by davidbannon** [comment] 2018-12-07 00:11
Ah, that makes sense, I used to work with someone who used that, long time ago. It was very unreliable back then......   Hope it works better now.

**Comment by xypd** [comment] 2018-12-07 01:52
haha, I love it, both the hardware keyboard and the OS. It's more like a tiny laptop then a phone. It's been great for me so far, issue here and there but like any device I suppose. Some new hardware is coming out Q1 next year so I might actually have something more modern hardware wise :D.

**Comment by davidbannon** [comment] 2019-12-20 07:04
I think I will close this to tidy up a bit.  Multilevel bullets are on my (published) ToDo list but its a hard problem, not one I am likely to commit a lot of time to in the immediate future.
Davo

**Comment by GunArm** [comment] 2021-08-19 00:56
Since there is only this request from a single person, I want to chime in and voice that at least for me, this is a **crucial** feature.   Tomboy itself is a surprisingly critical part of my life for going on nearly 20 years now, and without nested bullets, tomboy-ng unfortunately can not be a viable replacement.

I appreciate that others find this type of software so useful, and that you took it on yourself to re-implement it as the problems with GTK# and mono etc made getting tomboy working more and more difficult over the years.  But still I feel I should voice the perspective on the record so to speak, that for the listmaking, scratch planning, brainstorming of ideas and project architecting that I do in tomboy, makes _constant_ use of organizing items under other items -- multiple levels of bullets -- and without them it simply cannot serve the purpose that OG tomboy serves for me.

Here's a snip out of my current todo list
![Capture](https://user-images.githubusercontent.com/6316933/129988198-3b4b08eb-0992-44a8-a139-080e3379e7fc.PNG)
Nearly all of my thousands of notes are like this, and if I can't do this it is a vast downgrade -- I simply cannot use it for the things I have used tomboy for since the early 2000s.

I am always interested in a re-implementation of tomboy, since it's a miracle every time I manage to get old-tomboy installed on a new environment.  Getting a working install usually takes 10-12 hours of trial and error over several days, with the old busted dependancies.  Once installed, it's buggy with the task tray icon being invisible about 1/2 the time, since one of the last GTK updates around 2016.  Since 2016 i've been clicking an invisible space in my task tray to open my notes.  In spite of all this, I persist, because tomboy is the most useful thing ever.  But I know one day I will have a new environment and tomboy simply will not install anymore, even after the multiple days of trial and error.  I honestly don't know what I will do then.  For this reason I perpetually have my eye on tomboy-ng, and I check back every year or so to install tomboy-ng and see if nested bullets have been implemented, but as long as they have not, I simply do not have a viable path away from geriatric tomboy.

Anyway I don't want to sound whiney or entitled, or throw out the baby with the bathwater of your good work.  I just want to put it out there that there are people like me for whom this seemingly small peace of functionality is really the fulcrum of it's viability as a replacement.

**Comment by davidbannon** [comment] 2021-08-19 06:01
OK, I have reopened this issue.  Its a maybe.  As I have mentioned in the past, I am pretty unhappy with how kmemo handles bullets, I have added some pretty ugly code in there to may them work as I think they should. So, I worry that it means adding more ugly code of mine.
If I find myself looking for something to do ....
Davo

**Comment by aguador** [comment] 2021-08-20 11:37
Not to complicate your life, but this seems a reasonable feature request. I remember noting the lack of nested bullets at some point, but I've not been keeping very complicated notes lately. For project planning tasks and subtasks, outlines for writers or charting Dante's circles of hell this is an important and useful feature. As you have indicated this is not the first limitation you have encountered in kmemo, so maybe you could work with upstream? (Yeah, pretty cheeky comin' from a non-programmer.)

**Comment by GunArm** [comment] 2021-08-20 17:54
I wish there was something I could do to help.  I am inferring that kmemo is the engine of the "rich text box" tomboy-ng displays notes through?  And kmemo is one control out of the KControls project here https://github.com/kryslt/KControls
This part of their wiki talks about some of their funniness with bullets https://wiki.freepascal.org/KControls/KmemoNotes#Bullets

I tried to look at their source code to get an idea of how it works, if the bulletedness is a bit when it would need to be an integer, or maybe nested bullets are really just indented bullets, and if indents and bulletness are seperate kmemo block properties.  Just trying to understand the situation.  Sadly my unfamiliarity with any aspect of pascal (I didn't actually realize it was still an active language) is a barrier.

**Comment by davidbannon** [comment] 2021-08-21 00:32
Yes, you have summed it up there GunArm, KMemo does do nested bullets but overall, its bullets lack some of the behaviour we expect bullets to to do so I have added code to make up the difference. Its my code that does no do nested bullets.
And of course, this code is called each time the user presses a key so its critical it be fast.  So, I have taken the approach that it should do as little as possible. Sounds like I will have to reconsider.

I believe to best approach is going to be to go back and fix the underlying issues in KMemo rather that the pretty ugly wrapper I have used.

> pascal (I didn't actually realize it was still an active language) 

yes, still quite active. Has quite a large user base. While simple Pascal looks quite similar to simple C, the Object Pascal we use here is more to be compared to C++. And they are somewhat more different. The big advantage is the closely intergrated LCL, Lazarus Component Library and IDE that makes the cross platform GUI very easy.

Davo

**Comment by davidbannon** [comment] 2021-08-21 11:18
OK, yes, its possible. And perhaps not as hard as I decided back in the early stages of this project. 
But they cannot all be bullets, I must use a different 'character' for each level. I can use things like Bullets, Arabic Numerals, Roman Numerals, Letters. The Roman and Letters can be upper or lower case, this is what I have been playing with -

![bullets](https://user-images.githubusercontent.com/6291248/130320029-69fb63b5-b681-4505-a3f1-c7203221e2be.png)

Your comments welcome !

Davo

**Comment by aguador** [comment] 2021-08-22 08:49
Great news. That said I would not mix bullets and letters/numbers if possible. The latter suggest order/priority as well as hierarchy. I recall using bullets, hyphens (-) and then dots (.), even in ancient, pre-word processing days. This could be extended with the em-dash (—), perhaps mathematical signs like =, +, >. The asterisk is also possible, but might best be used at the highest level given its size. Others may have better ideas.

**Comment by davidbannon** [comment] 2021-08-22 13:46
Yep, agree. But to use other than the ones predefined in KMemo, I'll have to patch KMemo.  And that causes problems with my Debian and Ubuntu builds, using (eg) KMemo 'out of the box' makes things a lot easier.
During both builds, I get a live copy direct from TK's repository. If I want to patch it, its a case of applying that patch, completely hands off, during the remote build process.  These builds happen on Debian and Ubuntu remote machines you understand.
Davo

**Comment by xypd** [comment] 2021-08-22 14:28
Some nice progress here. So you're saying that your dev setup will break or cause issues if you change the KMemo bullets to something none debiab/ubuntu standard?

Cause I would be happy with some of the following, * ° • - — + > » or even a simple "."

So you can't not compile it on your setup?

This too has made it tough to sync all my note without it reformatting.
x

**Comment by aguador** [comment] 2021-08-22 15:03
> Yep, agree. But to use other than the ones predefined in KMemo, I'll have to patch KMemo. And that causes problems with my Debian and Ubuntu builds, using (eg) KMemo 'out of the box' makes things a lot easier.

Understood. I assume from the reply there is no numbered list defined in KMemo, which would be better than mixing.

xypd raises a good question about reformatting, which has a further implication: would KMemo actually reformat, or choke??? I see some nasty testing ahead... :-/

**Comment by davidbannon** [comment] 2021-08-23 01:40
xypd, no, its not a case of using debiab/ubuntu standard. Just of using the characters TK has chosen to use in KMemo.  KMemo is an external library linked to tomboy-ng at compile time.  The source is readily available and can be patched when I build -ng locally, on my laptop for example.

But when building as part of a Debian or Ubuntu source build, I submit my source code and scripts that know how to do the building. Those scripts go and get KMemo from its 'official' repository and then use it.  While I can add patching of kmemo to that process, it increases the risk of a build failure. And all that building happens out of my sight.  KMemo is a pretty complicated package, if I hack away at it, I'll need to do a lot of testing !

TK really describes this feature as "paragraph numbering". KMemo allows the use of several 'characters', but only one of them is not sequential, the bullet.  I believe I have to use a different character for each level so we can have only one non-sequential level.    

I will log an issue with TK and see if I am wrong about each level having to use its own character. He is a pretty busy guy but has helped me in the past.

Davo

**Comment by davidbannon** [comment] 2021-08-23 10:43
OK, like wow !
Less that 24 hours after I logged this, TK has come back with a solution !  I'll have to do some tests and get it lined up for Lazarus's Online Package Manager but right now and it looks pretty good.

Unlike fixes to Lazarus LCL, fixes to KMemo are available to use almost immediately !

I'll need to do those tests ....

https://github.com/kryslt/KControls/issues/35

Davo

**Comment by davidbannon** [comment] 2021-08-23 12:09
Here is a sample. TK has provided us with two extra 'bullets', I have altered the order a bit here and we still have lower case letters as a fourth level. Now, I don't see  a case for four levels anyway. But I note that xypd's sample does have four levels.  So, xypd, is using sequential lowercase OK at the fourth level ?

Personally, I have only ever used four levels of bullets in legal documents, and I don't think of tomboy-ng as the tool for that sort of work. But I am looking for your thoughts folks !

 Davo
![bullets](https://user-images.githubusercontent.com/6291248/130444237-82f3a5cd-7d36-46b9-98ec-d70cb29028f5.png)

**Comment by xypd** [comment] 2021-08-23 12:32
This sounds like great news! I would need to look on my other device to see really how many levels I use.

I think however this is very workable for daily use. So if this is what it needs to be I think I can live with that. I'm not sure how possible this requests would be, but could an preference option be added to change the the level order? So meaning I could choose apps wide to have square -> dots -> sequential for example?

I don't have an issue with sequential, since some other might find it useful.

Will response more about details in a few days, when I get to my device.

**Comment by GunArm** [comment] 2021-08-23 18:30
Been out through the weekend, so I just want to say I'm ecstatic with the progress.  I *really* appreciate your having taken time out of your life to address this.  I would have been _ok_ with the original nested things turning in to numbering, although it would not be my first choice, but atleast items could go under other items.

As for the current iteration, having checked over a lot of my notes, I saw a few times where I went out to 4 levels, but it was rare.  I'm grateful for the fact it goes out that far regardless of if the sigils turn into ordered letters.

My initial concern about the sequences though, is that I know WYSIWYG editors, even very basic ones, are hard to write and maintain, even google's built into gmail is not always perfect.  And autonumbering is weird even in big software like LibreOffice.  I find it miraculous when they don't do weird things.  For example, what happens if you have two sets of auto numbers, and then you delete the space between them?  Or if you have 1-5 (or a-e) and reduce the third one a level back, or put a space after the third one, do 4 and 5 become 1 and 2 like you'd expect, or does it leave you with a sequence starting at 4?  OTOH maybe it "just works", but I just know it can be rife with gotchas.

Frankly, even having multiple different character sigils for different bullet-levels isn't completely necessary to me, IE, if it was the same sigil at all levels I'd accept that.  It's nice that there are multiple sigils though.  But it's certainly not critical that they are fully unique at each level, so depending on code limitations, if it could just go back to bullet style 1 after level 3.  FWIW, that's how original tomboy works, it has 3 bullet symbols and just repeats the sequence at further levels.  But if, for whatever code-wise reason, it's easier to go to an incrementing 4th level that's fine too.  Just thinking how even though no-one requested incrementing, if it's in the software, someone will get neurotic about it and file bugs about oddities, which might be harder to fix than the original feature was to create .  So just saying looping sigils is another possibility.


Side note: Do you think the migration of notes between old tomboy and ng will be able to convert tomboy bullets to tomboy-ng bullets?

**Comment by davidbannon** [comment] 2021-08-24 06:06
GunArm, I have not tested how well the sequencial numbering works to be honest. I have had to some ubtrusive code around KMemo's "paragraph numbering" system to make it behave as we expect it to, things like backspacing at the beginning of a bullet line. I may need to do more if we have issues with the fourth level. But if thats the case, I think I will keep TK informed, he has been very helpfull here for a guy who said he does not want to work on KControls any more !

The issue is not really about reusing the bullet image itself, the software has a fixed number of 'slots' each has its own image. We could have them all with the same image, the limiting factor is the number of slots or levels defined. But TK has demonstarted that was reasonably easy to add two more....

Migration from Tomboy to tomboy-ng with extended bullets is my problem, should not be too hard.  Hardest thing will getting an instance of Tomboy going so I can see what the html looks like. If you have an existing note with multiple levels, posting it here would be a big help !

Davo

**Comment by davidbannon** [comment] 2021-08-24 06:11
>  could an preference option be added to change the the level order? 
@xypd - I would rather not, it would be another thing that needs to be looked up and dealt with on every key press. And that would slow things down. We have some very fast typists out there ...

Better IMHO, to decide on the best order now and 'hard wire' it that way.

Incidentally, the changes being made here (in my code, not TK's) to accommodate multiple levels should be a touch faster now that i understand a bit more about the levels. Thats nice !

Davo

**Comment by GunArm** [comment] 2021-08-24 15:45
I made a sample OG tomboy note and exported it to html.

Funny thing, github doesn't allow attaching html files
So I went to put it on pastebin.  And pastebin says it's offensive content lol.  I whittled the doc down, and eventually worked out that it's "http://beatniksoftware.com/tomboy" which is offensive, although not ""http://beatniksoftware.com/" or "tomboy".  Anyway pastebin literally would not let me paste this content.  Never seen that before, anyway I had to find a different pastbin site.

Let me know if this link doesn't work or anything: https://ghostbin.com/paste/GKvZ8

**Comment by davidbannon** [comment] 2021-08-25 00:20
Thanks GunArm, but what I need is the file in .note format, its xml but pretty different to html.  So, just the note please.
It will still have the content offensive to pastebin (??) so, maybe just zip it up ?
There is also an email address in the license file for me.

Davo

**Comment by GunArm** [comment] 2021-08-25 05:26
My mistake, not sure what I was thinking exporting it.  Here's the .note
[note.zip](https://github.com/tomboy-notes/tomboy-ng/files/7043895/note.zip)

**Comment by davidbannon** [comment] 2021-08-28 01:43
Ah, excellent news, I'll run with that then.
Been in C19 lockdown here now for a week so I have the time .....
Than GunArm !

Davo

**Comment by davidbannon** [comment] 2021-08-28 12:20
OK, I think I have it working as expected. I say 'think' because there is a a lot of new code in there. Not only new Bullet code but there is also relatively untested new code to do the regular note saves in a separate thread. So, I ask, you want to have a try with it ?  I have made packages I will use for my testing and can post them if you want to try. But there is an element of risk.

xypd - MacOS ?
GunArm - Windows ?

Davo

**Comment by GunArm** [comment] 2021-08-28 20:23
Yeah windows here.  If you've got a build I'll be happy to beat on it :)

**Comment by xypd** [comment] 2021-08-28 21:16
Yeah macOS is fine. I could also try linux in vm or on arm64. But mac would be the easiest at the moment

**Comment by davidbannon** [comment] 2021-08-29 07:31
OK, they are available from -

https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.33a

Look for the 0.33b in the file names.  I have tested superficially but, as I mentioned, some big changes in there.

@xypd, arm64 ?  What flavour are you using ?  I ship a -ng with armhf, for RasPi on RasPi OS but no 64bit version.  I suspect it might be hard to make both because I cross compile and it seems I can have either but not both on the same system. So, interested in how widely used the 64bit OS's are.

Davo

**Comment by xypd** [comment] 2021-08-29 14:10
I would try it on my PinePhone which can run multible distros. I actually already have it install on mobian (debian mobile DE), so maybe the .deb will work fine. The device has an [Allwinner A64](https://linux-sunxi.org/A64) chip in it. But on linux I would likely bootup my ubuntu virtualbox vm

**Comment by xypd** [comment] 2021-08-29 16:43
Look like Libgtk2.0-0 libc6 libcanberra-gtk-module are miss for the arm64 install. Just fyi.

After installing them, I was not able to install tomboy-ng armhf. Will give the mac OS a tried once I get time to backup my notes or maybe I can add it to another user account.

**Comment by davidbannon** [comment] 2021-08-30 09:25
>After installing them, I was not able to install tomboy-ng armhf.

No, the armhf is a 32bit system. You might be able to install all the necessary 32bit libraries but it would be pretty ugly !

It 'should' be possible to build a 64bit arm. But I have not tried, mainly because no demand  :-)

> Allwinner64

Is an arm chip too. So, won't work with the intel targeted packages.

Davo

**Comment by xypd** [comment] 2021-08-30 14:28
Ah I see thanks for that info. Never knew that about armhf.

**Comment by GunArm** [comment] 2021-08-30 18:09
I don't see a windows build for 33b.  I'm looking for an exe right?  I see rpm, deb, tgz.  Only one exe (for 33a)

**Comment by davidbannon** [comment] 2021-08-30 22:15
> I don't see a windows build for 33b. 

No, I don't know what I did wrong there, maybe i uploaded the 0.33a version again ?  Sorry, the one you want is now there, yes, its called 0.33b

Davo

**Comment by GunArm** [comment] 2021-08-30 23:53
Thanks.

Having the nested bullets is great.  Also my notes from tomboy all migrated and look good from a cursory glance.

Here, in no particular order of significance, are some oddities I noticed:
1.  If you bullet something, and then unbullet it, some indent is left over, which goes away when you close/reopen the note
![1](https://user-images.githubusercontent.com/6316933/131419517-2f59a3ae-2e12-41bf-8145-606ec972b321.png)

2.  There seems to be slightly more indent on the 8th bullet than the rest of them
![2](https://user-images.githubusercontent.com/6316933/131419557-d6cbec3f-182d-4db7-ab28-2b2452b4f95c.png)

3.  Migrating really deep bullets (deeper than I have ever used), the bullet level gets lost past level 6.  In this screenshot I went out to 9 only to test, knowing it was one more than supported, but would have expected 7 and 8 to increased and I guess 9 to be on level 8.
![3](https://user-images.githubusercontent.com/6316933/131419668-12ab2dca-7f16-46a3-ad39-7cd286259017.PNG)
Here are two .note files related to this one.  tomboy00* is the original tomboy note, tomboyng* is the note after it was opened in tomboy ng, and then I changed a char and changed it back to force a save.
[migrate-test.zip](https://github.com/tomboy-notes/tomboy-ng/files/7080159/migrate-test.zip)

4.  Maybe this is expected and can't be helped, but just to report, it looks like the incrementing numbers are global for the note
![4](https://user-images.githubusercontent.com/6316933/131419855-f63a38e3-8554-470d-aab0-369094877b9d.PNG)

**Comment by davidbannon** [comment] 2021-08-31 23:35
>If you bullet something, and then unbullet it, some indent is left over,

 Yes, it does.I dont know why I did not notice that, I have a fair idea of what causes it.

> There seems to be slightly more indent on the 8th bullet than the rest of them

Yep, found it.

> the bullet level gets lost past level 6.

That is strange. Calling no bullet level 0, I can go out to 8 and there it stops.  I get 7=Uppercase Roman; 8=Number; 9=Is the same numbers

**Comment by xypd** [comment] 2021-08-31 23:42
Great feedback GunArm. Sadly it might be a week before I have time to mess around with out changing my live setup.

**Comment by davidbannon** [comment] 2021-08-31 23:42
Accidental close .....

![levels](https://user-images.githubusercontent.com/6291248/131589188-1746c961-e719-47c0-93fb-a5ad7ebcbd37.png)

> incrementing numbers are global 

Yes, thats what made me go back to TK at KControls and request one more (non-sequential) bullet.  He has now done that and agrees more work is needed so what we see now is temporary.  I have supported all nine levels but think the latter ones are unusable. So, will advertise as having four. After that, its your decision to use them or not. But they will be at least saved as levels.

**Comment by xypd** [comment] 2021-08-31 23:46
Is it possible to make the solid circle first, a hollow circle second and then continue with what you have? For my taste the arrow call too much attention to itself. But I can live with that over no nested sub-bullets :).

**Comment by davidbannon** [comment] 2021-09-01 03:00
Yes, I agree that the large arrow is too large. But we have a limited number of slots and I felt that I should use the most prominent one first.  
Now, TK has come back to me with the further addition I requested and an observation that it needs more work. IMHO, we need at least four 'medium' bullets, support for beyond that is not a high priority but I want to allow it just in case someone has a specific need and I don't want to risk not saving their work.

I will take this up with TK and see if we can find a reasonable 'set' of four or five medium bullets.

Davo

**Comment by GunArm** [comment] 2021-09-01 04:03
> > the bullet level gets lost past level 6.
> 
> That is strange. Calling no bullet level 0, I can go out to 8 and there it stops. I get 7=Uppercase Roman; 8=Number; 9=Is the same numbers

Just to be clear: I can go out to 8 the way you describe in ng and it works fine, it was only migrating a tomboy-prime note to tomboy-ng which did that.  I don't want to give the impression that levels 7 and 8 don't work at all for me, they do.


FWIW about the big first arrow: it is big, but I could get used to it.  I also am with you that if one is more prominent than the others it should probably be the first one.

**Comment by davidbannon** [comment] 2021-09-01 04:37
> it was only migrating a tomboy-prime note to tomboy-ng which did that

OK, I did no get that initially. Seriously wonder why ?

> big first arrow

I keep telling myself I can get used to it too but I suspect I lie.

I have put a new model to TK that, I think, will make things better. Could even let the user choose.....

Davo

**Comment by davidbannon** [comment] 2021-09-14 10:22
Hi folks, TK is clearly pre-occupied at present, thought I would have a play with some alternative arrangements.  Attached is an image showing five levels (with the possibility of an additional three not very functional ones). I have chosen smaller bullet characters and will need to do some testing to ensure that they are widely available. Apparently thats not always the case ...

![bullets](https://user-images.githubusercontent.com/6291248/133240795-6c87db02-83db-4a50-9258-12842222c37d.png)

Davo

**Comment by GunArm** [comment] 2021-09-14 20:42
Not sure how you did it, but looks nice...

**Comment by davidbannon** [comment] 2021-10-30 11:11
Folks, an issue, TK, the author of KControls has found that in his locale, Czech, the bullet characters I have used do not show up in Windows. Assuming you are using Windows and the the 0.33e beta of tomboy-ng, could you please let me know where you live ?

Davo

**Comment by GunArm** [comment] 2021-11-01 15:21
Sure, I'm in the US, seems to work for me:
![image](https://user-images.githubusercontent.com/6316933/139696069-cb681065-d942-4d18-936e-4677aa1fcc93.png)

**Comment by aguador** [comment] 2021-11-03 23:07
Not a Win user, but decided to test 33e and noted something wonky. Made a mistake and decided to eliminate the level and redo it erasing with the backspace key. At every level except the first bulleted level when the first character of the bullet point is deleted, the cursor moves to the level above, but treats it as if it were the level removed, indenting it more and using the symbol for the lower level. See pic where the lower part shows how the penultimate level is changed with the removal of the one below. (Pic may not be worth 1000 words, but better than the description I just wrote.)

Not sure if that was intended behavior, but is not what I would have expected. The unindent shortcut, of course, quickly undoes this so it is not a catastrophe or (one supposes) an indication of impending Armegeddon.

When the top level is reached, ng removes the bullet point and moves the text to the left margin.

At some point using the keyboard shortcut to indent a level turned on **bold**. This happened several times, but could not be reproduced consistently, so I assume there is some magic sequence that leads to this -- just don't know what it is at the moment. 

Mageia 9 with Enlightenment 24.2 DE (and Spanish keyboard, if that matters).

![ng-bullets-2021-11-03](https://user-images.githubusercontent.com/8114758/140215348-1c0c9be3-5d53-4035-baa5-2ed4a199cf87.png)

**Comment by davidbannon** [comment] 2021-11-17 02:42
OK, fixed in newly released v0.34, will close this ticket.

Worth noting that this is, still, somewhat, a temp solution as in some locales, the bullet characters do not all work but until TK comes up with a better model, we are using my hacked version of KControls and it does seem to work for most people. I suspect, but have not proven, for the ones it does not work "out of the box" selecing a different "normal" font in tomboy-ng, will solve the problem.

Davo

**Closed** 2021-11-17 02:51 UTC

**Comment by GunArm** [comment] 2021-11-19 22:51
David, just want to give you a personal thank you for your work and time sacrifice on this.  I know it was hassle but it is very much appreciated!
